/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables;


import is.toxic.db.data.Keys;
import is.toxic.db.data.Public;
import is.toxic.db.data.tables.records.CryptoExchangeVariablesRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CryptoExchangeVariables extends TableImpl<CryptoExchangeVariablesRecord> {

    private static final long serialVersionUID = -972320535;

    /**
     * The reference instance of <code>public.crypto_exchange_variables</code>
     */
    public static final CryptoExchangeVariables CRYPTO_EXCHANGE_VARIABLES = new CryptoExchangeVariables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CryptoExchangeVariablesRecord> getRecordType() {
        return CryptoExchangeVariablesRecord.class;
    }

    /**
     * The column <code>public.crypto_exchange_variables.key</code>.
     */
    public final TableField<CryptoExchangeVariablesRecord, Integer> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.crypto_exchange_variables.value</code>.
     */
    public final TableField<CryptoExchangeVariablesRecord, BigDecimal> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * Create a <code>public.crypto_exchange_variables</code> table reference
     */
    public CryptoExchangeVariables() {
        this(DSL.name("crypto_exchange_variables"), null);
    }

    /**
     * Create an aliased <code>public.crypto_exchange_variables</code> table reference
     */
    public CryptoExchangeVariables(String alias) {
        this(DSL.name(alias), CRYPTO_EXCHANGE_VARIABLES);
    }

    /**
     * Create an aliased <code>public.crypto_exchange_variables</code> table reference
     */
    public CryptoExchangeVariables(Name alias) {
        this(alias, CRYPTO_EXCHANGE_VARIABLES);
    }

    private CryptoExchangeVariables(Name alias, Table<CryptoExchangeVariablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private CryptoExchangeVariables(Name alias, Table<CryptoExchangeVariablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> CryptoExchangeVariables(Table<O> child, ForeignKey<O, CryptoExchangeVariablesRecord> key) {
        super(child, key, CRYPTO_EXCHANGE_VARIABLES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CryptoExchangeVariablesRecord> getPrimaryKey() {
        return Keys.PK_CRYPTO_EXCHANGE_VARIABLES;
    }

    @Override
    public List<UniqueKey<CryptoExchangeVariablesRecord>> getKeys() {
        return Arrays.<UniqueKey<CryptoExchangeVariablesRecord>>asList(Keys.PK_CRYPTO_EXCHANGE_VARIABLES);
    }

    @Override
    public CryptoExchangeVariables as(String alias) {
        return new CryptoExchangeVariables(DSL.name(alias), this);
    }

    @Override
    public CryptoExchangeVariables as(Name alias) {
        return new CryptoExchangeVariables(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CryptoExchangeVariables rename(String name) {
        return new CryptoExchangeVariables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CryptoExchangeVariables rename(Name name) {
        return new CryptoExchangeVariables(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, BigDecimal> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
