/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import is.toxic.db.data.Indexes;
import is.toxic.db.data.Keys;
import is.toxic.db.data.Public;
import is.toxic.db.data.tables.records.UserDatasRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDatas extends TableImpl<UserDatasRecord> {

    private static final long serialVersionUID = -731019394;

    /**
     * The reference instance of <code>public.user_datas</code>
     */
    public static final UserDatas USER_DATAS = new UserDatas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDatasRecord> getRecordType() {
        return UserDatasRecord.class;
    }

    /**
     * The column <code>public.user_datas.id</code>.
     */
    public final TableField<UserDatasRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user_datas.user_id</code>.
     */
    public final TableField<UserDatasRecord, String> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_datas.user_name</code>.
     */
    public final TableField<UserDatasRecord, String> USER_NAME = createField(DSL.name("user_name"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_datas.trades_avg_amount</code>.
     */
    public final TableField<UserDatasRecord, BigDecimal> TRADES_AVG_AMOUNT = createField(DSL.name("trades_avg_amount"), org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.trades_count</code>.
     */
    public final TableField<UserDatasRecord, Long> TRADES_COUNT = createField(DSL.name("trades_count"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.counterpartys_count</code>.
     */
    public final TableField<UserDatasRecord, Long> COUNTERPARTYS_COUNT = createField(DSL.name("counterpartys_count"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.response_rate</code>.
     */
    public final TableField<UserDatasRecord, BigDecimal> RESPONSE_RATE = createField(DSL.name("response_rate"), org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.first_trade_date</code>.
     */
    public final TableField<UserDatasRecord, LocalDateTime> FIRST_TRADE_DATE = createField(DSL.name("first_trade_date"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.user_datas.trusted_count</code>.
     */
    public final TableField<UserDatasRecord, Long> TRUSTED_COUNT = createField(DSL.name("trusted_count"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.blocked_count</code>.
     */
    public final TableField<UserDatasRecord, Long> BLOCKED_COUNT = createField(DSL.name("blocked_count"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.avg_delay_seconds</code>.
     */
    public final TableField<UserDatasRecord, Long> AVG_DELAY_SECONDS = createField(DSL.name("avg_delay_seconds"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.median_delay_seconds</code>.
     */
    public final TableField<UserDatasRecord, Long> MEDIAN_DELAY_SECONDS = createField(DSL.name("median_delay_seconds"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.time_zone</code>.
     */
    public final TableField<UserDatasRecord, String> TIME_ZONE = createField(DSL.name("time_zone"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_datas.introduction</code>.
     */
    public final TableField<UserDatasRecord, String> INTRODUCTION = createField(DSL.name("introduction"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_datas.site</code>.
     */
    public final TableField<UserDatasRecord, String> SITE = createField(DSL.name("site"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_datas.sales_disabled</code>.
     */
    public final TableField<UserDatasRecord, Boolean> SALES_DISABLED = createField(DSL.name("sales_disabled"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.buys_disabled</code>.
     */
    public final TableField<UserDatasRecord, Boolean> BUYS_DISABLED = createField(DSL.name("buys_disabled"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.send_sms_contacts_notification</code>.
     */
    public final TableField<UserDatasRecord, Boolean> SEND_SMS_CONTACTS_NOTIFICATION = createField(DSL.name("send_sms_contacts_notification"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.send_sms_payments_notifications</code>.
     */
    public final TableField<UserDatasRecord, Boolean> SEND_SMS_PAYMENTS_NOTIFICATIONS = createField(DSL.name("send_sms_payments_notifications"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.send_crypto_deposit_notifications</code>.
     */
    public final TableField<UserDatasRecord, Boolean> SEND_CRYPTO_DEPOSIT_NOTIFICATIONS = createField(DSL.name("send_crypto_deposit_notifications"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.show_me_as_having_verified_real_name</code>.
     */
    public final TableField<UserDatasRecord, Boolean> SHOW_ME_AS_HAVING_VERIFIED_REAL_NAME = createField(DSL.name("show_me_as_having_verified_real_name"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.disable_confidential_information_from_email</code>.
     */
    public final TableField<UserDatasRecord, Boolean> DISABLE_CONFIDENTIAL_INFORMATION_FROM_EMAIL = createField(DSL.name("disable_confidential_information_from_email"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.enable_web_notifications</code>.
     */
    public final TableField<UserDatasRecord, Boolean> ENABLE_WEB_NOTIFICATIONS = createField(DSL.name("enable_web_notifications"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.created_at</code>.
     */
    public final TableField<UserDatasRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.jira_creds_id</code>.
     */
    public final TableField<UserDatasRecord, Long> JIRA_CREDS_ID = createField(DSL.name("jira_creds_id"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user_datas.is_anonymous</code>.
     */
    public final TableField<UserDatasRecord, Boolean> IS_ANONYMOUS = createField(DSL.name("is_anonymous"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_datas.invoice_average_amount</code>.
     */
    public final TableField<UserDatasRecord, BigDecimal> INVOICE_AVERAGE_AMOUNT = createField(DSL.name("invoice_average_amount"), org.jooq.impl.SQLDataType.NUMERIC.nullable(false).defaultValue(org.jooq.impl.DSL.field("0.0", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>public.user_datas.invoice_payments_count</code>.
     */
    public final TableField<UserDatasRecord, Integer> INVOICE_PAYMENTS_COUNT = createField(DSL.name("invoice_payments_count"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.user_datas.invoice_response_rate</code>.
     */
    public final TableField<UserDatasRecord, BigDecimal> INVOICE_RESPONSE_RATE = createField(DSL.name("invoice_response_rate"), org.jooq.impl.SQLDataType.NUMERIC.nullable(false).defaultValue(org.jooq.impl.DSL.field("0.0", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>public.user_datas.invoices_created_count</code>.
     */
    public final TableField<UserDatasRecord, Integer> INVOICES_CREATED_COUNT = createField(DSL.name("invoices_created_count"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.user_datas.invoices_sum_amount</code>.
     */
    public final TableField<UserDatasRecord, BigDecimal> INVOICES_SUM_AMOUNT = createField(DSL.name("invoices_sum_amount"), org.jooq.impl.SQLDataType.NUMERIC.nullable(false).defaultValue(org.jooq.impl.DSL.field("0.0", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>public.user_datas.is_deleted</code>.
     */
    public final TableField<UserDatasRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.user_datas</code> table reference
     */
    public UserDatas() {
        this(DSL.name("user_datas"), null);
    }

    /**
     * Create an aliased <code>public.user_datas</code> table reference
     */
    public UserDatas(String alias) {
        this(DSL.name(alias), USER_DATAS);
    }

    /**
     * Create an aliased <code>public.user_datas</code> table reference
     */
    public UserDatas(Name alias) {
        this(alias, USER_DATAS);
    }

    private UserDatas(Name alias, Table<UserDatasRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserDatas(Name alias, Table<UserDatasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> UserDatas(Table<O> child, ForeignKey<O, UserDatasRecord> key) {
        super(child, key, USER_DATAS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IX_USER_DATAS_JIRA_CREDS_ID, Indexes.IX_USER_DATAS_USER_ID, Indexes.IX_USER_DATAS_USER_NAME);
    }

    @Override
    public Identity<UserDatasRecord, Long> getIdentity() {
        return Keys.IDENTITY_USER_DATAS;
    }

    @Override
    public UniqueKey<UserDatasRecord> getPrimaryKey() {
        return Keys.PK_USER_DATAS;
    }

    @Override
    public List<UniqueKey<UserDatasRecord>> getKeys() {
        return Arrays.<UniqueKey<UserDatasRecord>>asList(Keys.PK_USER_DATAS);
    }

    @Override
    public List<ForeignKey<UserDatasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserDatasRecord, ?>>asList(Keys.USER_DATAS__FK_USER_DATAS_JIRA_CREDS_JIRA_CREDS_ID);
    }

    public JiraCreds jiraCreds() {
        return new JiraCreds(this, Keys.USER_DATAS__FK_USER_DATAS_JIRA_CREDS_JIRA_CREDS_ID);
    }

    @Override
    public UserDatas as(String alias) {
        return new UserDatas(DSL.name(alias), this);
    }

    @Override
    public UserDatas as(Name alias) {
        return new UserDatas(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDatas rename(String name) {
        return new UserDatas(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDatas rename(Name name) {
        return new UserDatas(name, null);
    }
}
