/*
 * This file is generated by jOOQ.
 */
package ru.toxic.db.data;


import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.toxic.db.data.tables.AdMetadata;
import ru.toxic.db.data.tables.AdMetadataSnapshot;
import ru.toxic.db.data.tables.AdvertisementSnapshot;
import ru.toxic.db.data.tables.Advertisements;
import ru.toxic.db.data.tables.AvgPrices;
import ru.toxic.db.data.tables.Balances;
import ru.toxic.db.data.tables.BlockedUsers;
import ru.toxic.db.data.tables.BtcCoreWallets;
import ru.toxic.db.data.tables.Complaints;
import ru.toxic.db.data.tables.CryptoExchangeVariables;
import ru.toxic.db.data.tables.DealMessage;
import ru.toxic.db.data.tables.Deals;
import ru.toxic.db.data.tables.Disputes;
import ru.toxic.db.data.tables.Feedbacks;
import ru.toxic.db.data.tables.FiatExchangeVariables;
import ru.toxic.db.data.tables.InAddresses;
import ru.toxic.db.data.tables.InTransactions;
import ru.toxic.db.data.tables.InvoicePayments;
import ru.toxic.db.data.tables.Invoices;
import ru.toxic.db.data.tables.JiraCreds;
import ru.toxic.db.data.tables.LastAdSearchParams;
import ru.toxic.db.data.tables.OutTransactionRequests;
import ru.toxic.db.data.tables.OutTransactions;
import ru.toxic.db.data.tables.TimeTableItemSnapshot;
import ru.toxic.db.data.tables.TimeTables;
import ru.toxic.db.data.tables.TrustedUsers;
import ru.toxic.db.data.tables.UserDataSnapshot;
import ru.toxic.db.data.tables.UserDatas;
import ru.toxic.db.data.tables.UserEvents;
import ru.toxic.db.data.tables.VariablesMetadata;
import ru.toxic.db.data.tables.__Efmigrationshistory;
import ru.toxic.db.data.tables.records.AdMetadataRecord;
import ru.toxic.db.data.tables.records.AdMetadataSnapshotRecord;
import ru.toxic.db.data.tables.records.AdvertisementSnapshotRecord;
import ru.toxic.db.data.tables.records.AdvertisementsRecord;
import ru.toxic.db.data.tables.records.AvgPricesRecord;
import ru.toxic.db.data.tables.records.BalancesRecord;
import ru.toxic.db.data.tables.records.BlockedUsersRecord;
import ru.toxic.db.data.tables.records.BtcCoreWalletsRecord;
import ru.toxic.db.data.tables.records.ComplaintsRecord;
import ru.toxic.db.data.tables.records.CryptoExchangeVariablesRecord;
import ru.toxic.db.data.tables.records.DealMessageRecord;
import ru.toxic.db.data.tables.records.DealsRecord;
import ru.toxic.db.data.tables.records.DisputesRecord;
import ru.toxic.db.data.tables.records.FeedbacksRecord;
import ru.toxic.db.data.tables.records.FiatExchangeVariablesRecord;
import ru.toxic.db.data.tables.records.InAddressesRecord;
import ru.toxic.db.data.tables.records.InTransactionsRecord;
import ru.toxic.db.data.tables.records.InvoicePaymentsRecord;
import ru.toxic.db.data.tables.records.InvoicesRecord;
import ru.toxic.db.data.tables.records.JiraCredsRecord;
import ru.toxic.db.data.tables.records.LastAdSearchParamsRecord;
import ru.toxic.db.data.tables.records.OutTransactionRequestsRecord;
import ru.toxic.db.data.tables.records.OutTransactionsRecord;
import ru.toxic.db.data.tables.records.TimeTableItemSnapshotRecord;
import ru.toxic.db.data.tables.records.TimeTablesRecord;
import ru.toxic.db.data.tables.records.TrustedUsersRecord;
import ru.toxic.db.data.tables.records.UserDataSnapshotRecord;
import ru.toxic.db.data.tables.records.UserDatasRecord;
import ru.toxic.db.data.tables.records.UserEventsRecord;
import ru.toxic.db.data.tables.records.VariablesMetadataRecord;
import ru.toxic.db.data.tables.records.__EfmigrationshistoryRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AdMetadataRecord, Long> IDENTITY_AD_METADATA = Identities0.IDENTITY_AD_METADATA;
    public static final Identity<AdMetadataSnapshotRecord, Long> IDENTITY_AD_METADATA_SNAPSHOT = Identities0.IDENTITY_AD_METADATA_SNAPSHOT;
    public static final Identity<AdvertisementSnapshotRecord, Long> IDENTITY_ADVERTISEMENT_SNAPSHOT = Identities0.IDENTITY_ADVERTISEMENT_SNAPSHOT;
    public static final Identity<AdvertisementsRecord, Long> IDENTITY_ADVERTISEMENTS = Identities0.IDENTITY_ADVERTISEMENTS;
    public static final Identity<AvgPricesRecord, Integer> IDENTITY_AVG_PRICES = Identities0.IDENTITY_AVG_PRICES;
    public static final Identity<BalancesRecord, Long> IDENTITY_BALANCES = Identities0.IDENTITY_BALANCES;
    public static final Identity<BlockedUsersRecord, Long> IDENTITY_BLOCKED_USERS = Identities0.IDENTITY_BLOCKED_USERS;
    public static final Identity<ComplaintsRecord, Long> IDENTITY_COMPLAINTS = Identities0.IDENTITY_COMPLAINTS;
    public static final Identity<DealMessageRecord, Long> IDENTITY_DEAL_MESSAGE = Identities0.IDENTITY_DEAL_MESSAGE;
    public static final Identity<DealsRecord, Long> IDENTITY_DEALS = Identities0.IDENTITY_DEALS;
    public static final Identity<DisputesRecord, Long> IDENTITY_DISPUTES = Identities0.IDENTITY_DISPUTES;
    public static final Identity<FeedbacksRecord, Long> IDENTITY_FEEDBACKS = Identities0.IDENTITY_FEEDBACKS;
    public static final Identity<InAddressesRecord, Long> IDENTITY_IN_ADDRESSES = Identities0.IDENTITY_IN_ADDRESSES;
    public static final Identity<InTransactionsRecord, Long> IDENTITY_IN_TRANSACTIONS = Identities0.IDENTITY_IN_TRANSACTIONS;
    public static final Identity<InvoicePaymentsRecord, Long> IDENTITY_INVOICE_PAYMENTS = Identities0.IDENTITY_INVOICE_PAYMENTS;
    public static final Identity<InvoicesRecord, Long> IDENTITY_INVOICES = Identities0.IDENTITY_INVOICES;
    public static final Identity<JiraCredsRecord, Long> IDENTITY_JIRA_CREDS = Identities0.IDENTITY_JIRA_CREDS;
    public static final Identity<LastAdSearchParamsRecord, Long> IDENTITY_LAST_AD_SEARCH_PARAMS = Identities0.IDENTITY_LAST_AD_SEARCH_PARAMS;
    public static final Identity<OutTransactionRequestsRecord, Long> IDENTITY_OUT_TRANSACTION_REQUESTS = Identities0.IDENTITY_OUT_TRANSACTION_REQUESTS;
    public static final Identity<OutTransactionsRecord, Long> IDENTITY_OUT_TRANSACTIONS = Identities0.IDENTITY_OUT_TRANSACTIONS;
    public static final Identity<TimeTableItemSnapshotRecord, Long> IDENTITY_TIME_TABLE_ITEM_SNAPSHOT = Identities0.IDENTITY_TIME_TABLE_ITEM_SNAPSHOT;
    public static final Identity<TimeTablesRecord, Long> IDENTITY_TIME_TABLES = Identities0.IDENTITY_TIME_TABLES;
    public static final Identity<TrustedUsersRecord, Long> IDENTITY_TRUSTED_USERS = Identities0.IDENTITY_TRUSTED_USERS;
    public static final Identity<UserDataSnapshotRecord, Long> IDENTITY_USER_DATA_SNAPSHOT = Identities0.IDENTITY_USER_DATA_SNAPSHOT;
    public static final Identity<UserDatasRecord, Long> IDENTITY_USER_DATAS = Identities0.IDENTITY_USER_DATAS;
    public static final Identity<UserEventsRecord, Long> IDENTITY_USER_EVENTS = Identities0.IDENTITY_USER_EVENTS;
    public static final Identity<VariablesMetadataRecord, Integer> IDENTITY_VARIABLES_METADATA = Identities0.IDENTITY_VARIABLES_METADATA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<__EfmigrationshistoryRecord> PK___EFMIGRATIONSHISTORY = UniqueKeys0.PK___EFMIGRATIONSHISTORY;
    public static final UniqueKey<AdMetadataRecord> PK_AD_METADATA = UniqueKeys0.PK_AD_METADATA;
    public static final UniqueKey<AdMetadataSnapshotRecord> PK_AD_METADATA_SNAPSHOT = UniqueKeys0.PK_AD_METADATA_SNAPSHOT;
    public static final UniqueKey<AdvertisementSnapshotRecord> PK_ADVERTISEMENT_SNAPSHOT = UniqueKeys0.PK_ADVERTISEMENT_SNAPSHOT;
    public static final UniqueKey<AdvertisementsRecord> PK_ADVERTISEMENTS = UniqueKeys0.PK_ADVERTISEMENTS;
    public static final UniqueKey<AvgPricesRecord> PK_AVG_PRICES = UniqueKeys0.PK_AVG_PRICES;
    public static final UniqueKey<BalancesRecord> PK_BALANCES = UniqueKeys0.PK_BALANCES;
    public static final UniqueKey<BlockedUsersRecord> PK_BLOCKED_USERS = UniqueKeys0.PK_BLOCKED_USERS;
    public static final UniqueKey<BtcCoreWalletsRecord> PK_BTC_CORE_WALLETS = UniqueKeys0.PK_BTC_CORE_WALLETS;
    public static final UniqueKey<ComplaintsRecord> PK_COMPLAINTS = UniqueKeys0.PK_COMPLAINTS;
    public static final UniqueKey<CryptoExchangeVariablesRecord> PK_CRYPTO_EXCHANGE_VARIABLES = UniqueKeys0.PK_CRYPTO_EXCHANGE_VARIABLES;
    public static final UniqueKey<DealMessageRecord> PK_DEAL_MESSAGE = UniqueKeys0.PK_DEAL_MESSAGE;
    public static final UniqueKey<DealsRecord> PK_DEALS = UniqueKeys0.PK_DEALS;
    public static final UniqueKey<DisputesRecord> PK_DISPUTES = UniqueKeys0.PK_DISPUTES;
    public static final UniqueKey<FeedbacksRecord> PK_FEEDBACKS = UniqueKeys0.PK_FEEDBACKS;
    public static final UniqueKey<FiatExchangeVariablesRecord> PK_FIAT_EXCHANGE_VARIABLES = UniqueKeys0.PK_FIAT_EXCHANGE_VARIABLES;
    public static final UniqueKey<InAddressesRecord> PK_IN_ADDRESSES = UniqueKeys0.PK_IN_ADDRESSES;
    public static final UniqueKey<InTransactionsRecord> PK_IN_TRANSACTIONS = UniqueKeys0.PK_IN_TRANSACTIONS;
    public static final UniqueKey<InvoicePaymentsRecord> PK_INVOICE_PAYMENTS = UniqueKeys0.PK_INVOICE_PAYMENTS;
    public static final UniqueKey<InvoicesRecord> PK_INVOICES = UniqueKeys0.PK_INVOICES;
    public static final UniqueKey<JiraCredsRecord> PK_JIRA_CREDS = UniqueKeys0.PK_JIRA_CREDS;
    public static final UniqueKey<LastAdSearchParamsRecord> PK_LAST_AD_SEARCH_PARAMS = UniqueKeys0.PK_LAST_AD_SEARCH_PARAMS;
    public static final UniqueKey<OutTransactionRequestsRecord> PK_OUT_TRANSACTION_REQUESTS = UniqueKeys0.PK_OUT_TRANSACTION_REQUESTS;
    public static final UniqueKey<OutTransactionsRecord> PK_OUT_TRANSACTIONS = UniqueKeys0.PK_OUT_TRANSACTIONS;
    public static final UniqueKey<TimeTableItemSnapshotRecord> PK_TIME_TABLE_ITEM_SNAPSHOT = UniqueKeys0.PK_TIME_TABLE_ITEM_SNAPSHOT;
    public static final UniqueKey<TimeTablesRecord> PK_TIME_TABLES = UniqueKeys0.PK_TIME_TABLES;
    public static final UniqueKey<TrustedUsersRecord> PK_TRUSTED_USERS = UniqueKeys0.PK_TRUSTED_USERS;
    public static final UniqueKey<UserDataSnapshotRecord> PK_USER_DATA_SNAPSHOT = UniqueKeys0.PK_USER_DATA_SNAPSHOT;
    public static final UniqueKey<UserDatasRecord> PK_USER_DATAS = UniqueKeys0.PK_USER_DATAS;
    public static final UniqueKey<UserEventsRecord> PK_USER_EVENTS = UniqueKeys0.PK_USER_EVENTS;
    public static final UniqueKey<VariablesMetadataRecord> PK_VARIABLES_METADATA = UniqueKeys0.PK_VARIABLES_METADATA;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AdMetadataRecord, AdvertisementsRecord> AD_METADATA__FK_AD_METADATA_ADVERTISEMENTS_ADVERTISEMENT_ID = ForeignKeys0.AD_METADATA__FK_AD_METADATA_ADVERTISEMENTS_ADVERTISEMENT_ID;
    public static final ForeignKey<AdvertisementSnapshotRecord, UserDataSnapshotRecord> ADVERTISEMENT_SNAPSHOT__FK_ADVERTISEMENT_SNAPSHOT_USER_DATA_SNAPSHOT_OWNER_KEY = ForeignKeys0.ADVERTISEMENT_SNAPSHOT__FK_ADVERTISEMENT_SNAPSHOT_USER_DATA_SNAPSHOT_OWNER_KEY;
    public static final ForeignKey<AdvertisementSnapshotRecord, AdMetadataSnapshotRecord> ADVERTISEMENT_SNAPSHOT__FK_ADVERTISEMENT_SNAPSHOT_AD_METADATA_SNAPSHOT_METADATA_KEY = ForeignKeys0.ADVERTISEMENT_SNAPSHOT__FK_ADVERTISEMENT_SNAPSHOT_AD_METADATA_SNAPSHOT_METADATA_KEY;
    public static final ForeignKey<AdvertisementsRecord, UserDatasRecord> ADVERTISEMENTS__FK_ADVERTISEMENTS_USER_DATAS_OWNER_ID = ForeignKeys0.ADVERTISEMENTS__FK_ADVERTISEMENTS_USER_DATAS_OWNER_ID;
    public static final ForeignKey<BalancesRecord, UserDatasRecord> BALANCES__FK_BALANCES_USER_DATAS_OWNER_ID = ForeignKeys0.BALANCES__FK_BALANCES_USER_DATAS_OWNER_ID;
    public static final ForeignKey<BlockedUsersRecord, UserDatasRecord> BLOCKED_USERS__FK_BLOCKED_USERS_USER_DATAS_OWNER_ID = ForeignKeys0.BLOCKED_USERS__FK_BLOCKED_USERS_USER_DATAS_OWNER_ID;
    public static final ForeignKey<BlockedUsersRecord, UserDatasRecord> BLOCKED_USERS__FK_BLOCKED_USERS_USER_DATAS_USER_ID = ForeignKeys0.BLOCKED_USERS__FK_BLOCKED_USERS_USER_DATAS_USER_ID;
    public static final ForeignKey<DealMessageRecord, UserDatasRecord> DEAL_MESSAGE__FK_DEAL_MESSAGE_USER_DATAS_OWNER_ID = ForeignKeys0.DEAL_MESSAGE__FK_DEAL_MESSAGE_USER_DATAS_OWNER_ID;
    public static final ForeignKey<DealMessageRecord, DealsRecord> DEAL_MESSAGE__FK_DEAL_MESSAGE_DEALS_DEAL_ID = ForeignKeys0.DEAL_MESSAGE__FK_DEAL_MESSAGE_DEALS_DEAL_ID;
    public static final ForeignKey<DealsRecord, FeedbacksRecord> DEALS__FK_DEALS_FEEDBACKS_AD_OWNER_FEED_BACK_ID = ForeignKeys0.DEALS__FK_DEALS_FEEDBACKS_AD_OWNER_FEED_BACK_ID;
    public static final ForeignKey<DealsRecord, FeedbacksRecord> DEALS__FK_DEALS_FEEDBACKS_INITIATOR_FEEDBACK_ID = ForeignKeys0.DEALS__FK_DEALS_FEEDBACKS_INITIATOR_FEEDBACK_ID;
    public static final ForeignKey<DealsRecord, DisputesRecord> DEALS__FK_DEALS_DISPUTES_DISPUTE_ID = ForeignKeys0.DEALS__FK_DEALS_DISPUTES_DISPUTE_ID;
    public static final ForeignKey<DealsRecord, AdvertisementSnapshotRecord> DEALS__FK_DEALS_ADVERTISEMENT_SNAPSHOT_AD_SNAPSHOT_KEY = ForeignKeys0.DEALS__FK_DEALS_ADVERTISEMENT_SNAPSHOT_AD_SNAPSHOT_KEY;
    public static final ForeignKey<DealsRecord, UserDataSnapshotRecord> DEALS__FK_DEALS_USER_DATA_SNAPSHOT_INITIATOR_SNAPSHOT_KEY = ForeignKeys0.DEALS__FK_DEALS_USER_DATA_SNAPSHOT_INITIATOR_SNAPSHOT_KEY;
    public static final ForeignKey<FeedbacksRecord, UserDatasRecord> FEEDBACKS__FK_FEEDBACKS_USER_DATAS_FROM_ID = ForeignKeys0.FEEDBACKS__FK_FEEDBACKS_USER_DATAS_FROM_ID;
    public static final ForeignKey<FeedbacksRecord, UserDatasRecord> FEEDBACKS__FK_FEEDBACKS_USER_DATAS_TO_ID = ForeignKeys0.FEEDBACKS__FK_FEEDBACKS_USER_DATAS_TO_ID;
    public static final ForeignKey<InAddressesRecord, BtcCoreWalletsRecord> IN_ADDRESSES__FK_IN_ADDRESSES_BTC_CORE_WALLETS_BTC_CORE_WALLET_PRIVATE_KEY = ForeignKeys0.IN_ADDRESSES__FK_IN_ADDRESSES_BTC_CORE_WALLETS_BTC_CORE_WALLET_PRIVATE_KEY;
    public static final ForeignKey<InAddressesRecord, UserDatasRecord> IN_ADDRESSES__FK_IN_ADDRESSES_USER_DATAS_OWNER_ID = ForeignKeys0.IN_ADDRESSES__FK_IN_ADDRESSES_USER_DATAS_OWNER_ID;
    public static final ForeignKey<InTransactionsRecord, InAddressesRecord> IN_TRANSACTIONS__FK_IN_TRANSACTIONS_IN_ADDRESSES_ADDRESS_ID = ForeignKeys0.IN_TRANSACTIONS__FK_IN_TRANSACTIONS_IN_ADDRESSES_ADDRESS_ID;
    public static final ForeignKey<InvoicePaymentsRecord, InvoicesRecord> INVOICE_PAYMENTS__FK_INVOICE_PAYMENTS_INVOICES_INVOICE_FK = ForeignKeys0.INVOICE_PAYMENTS__FK_INVOICE_PAYMENTS_INVOICES_INVOICE_FK;
    public static final ForeignKey<InvoicePaymentsRecord, UserDatasRecord> INVOICE_PAYMENTS__FK_INVOICE_PAYMENTS_USER_DATAS_USER_DATA_FK = ForeignKeys0.INVOICE_PAYMENTS__FK_INVOICE_PAYMENTS_USER_DATAS_USER_DATA_FK;
    public static final ForeignKey<InvoicesRecord, UserDatasRecord> INVOICES__FK_INVOICES_USER_DATAS_OWNER_FK = ForeignKeys0.INVOICES__FK_INVOICES_USER_DATAS_OWNER_FK;
    public static final ForeignKey<InvoicesRecord, UserDatasRecord> INVOICES__FK_INVOICES_USER_DATAS_TARGET_USER_FK = ForeignKeys0.INVOICES__FK_INVOICES_USER_DATAS_TARGET_USER_FK;
    public static final ForeignKey<LastAdSearchParamsRecord, UserDatasRecord> LAST_AD_SEARCH_PARAMS__FK_LAST_AD_SEARCH_PARAMS_USER_DATAS_OWNER_FK = ForeignKeys0.LAST_AD_SEARCH_PARAMS__FK_LAST_AD_SEARCH_PARAMS_USER_DATAS_OWNER_FK;
    public static final ForeignKey<OutTransactionRequestsRecord, UserDatasRecord> OUT_TRANSACTION_REQUESTS__FK_OUT_TRANSACTION_REQUESTS_USER_DATAS_OWNER_ID = ForeignKeys0.OUT_TRANSACTION_REQUESTS__FK_OUT_TRANSACTION_REQUESTS_USER_DATAS_OWNER_ID;
    public static final ForeignKey<OutTransactionRequestsRecord, BtcCoreWalletsRecord> OUT_TRANSACTION_REQUESTS__FK_OUT_TRANSACTION_REQUESTS_BTC_CORE_WALLETS_BTC_CORE_WALLET_P_7e = ForeignKeys0.OUT_TRANSACTION_REQUESTS__FK_OUT_TRANSACTION_REQUESTS_BTC_CORE_WALLETS_BTC_CORE_WALLET_P_7e;
    public static final ForeignKey<OutTransactionsRecord, BtcCoreWalletsRecord> OUT_TRANSACTIONS__FK_OUT_TRANSACTIONS_BTC_CORE_WALLETS_WALLET_PRIVATE_KEY = ForeignKeys0.OUT_TRANSACTIONS__FK_OUT_TRANSACTIONS_BTC_CORE_WALLETS_WALLET_PRIVATE_KEY;
    public static final ForeignKey<OutTransactionsRecord, OutTransactionRequestsRecord> OUT_TRANSACTIONS__FK_OUT_TRANSACTIONS_OUT_TRANSACTION_REQUESTS_REQUEST_ID = ForeignKeys0.OUT_TRANSACTIONS__FK_OUT_TRANSACTIONS_OUT_TRANSACTION_REQUESTS_REQUEST_ID;
    public static final ForeignKey<TimeTableItemSnapshotRecord, AdvertisementSnapshotRecord> TIME_TABLE_ITEM_SNAPSHOT__FK_TIME_TABLE_ITEM_SNAPSHOT_ADVERTISEMENT_SNAPSHOT_ADVERTISEME_7e = ForeignKeys0.TIME_TABLE_ITEM_SNAPSHOT__FK_TIME_TABLE_ITEM_SNAPSHOT_ADVERTISEMENT_SNAPSHOT_ADVERTISEME_7e;
    public static final ForeignKey<TimeTablesRecord, AdvertisementsRecord> TIME_TABLES__FK_TIME_TABLES_ADVERTISEMENTS_ADVERTISEMENT_ID = ForeignKeys0.TIME_TABLES__FK_TIME_TABLES_ADVERTISEMENTS_ADVERTISEMENT_ID;
    public static final ForeignKey<TrustedUsersRecord, UserDatasRecord> TRUSTED_USERS__FK_TRUSTED_USERS_USER_DATAS_OWNER_ID = ForeignKeys0.TRUSTED_USERS__FK_TRUSTED_USERS_USER_DATAS_OWNER_ID;
    public static final ForeignKey<TrustedUsersRecord, UserDatasRecord> TRUSTED_USERS__FK_TRUSTED_USERS_USER_DATAS_USER_ID = ForeignKeys0.TRUSTED_USERS__FK_TRUSTED_USERS_USER_DATAS_USER_ID;
    public static final ForeignKey<UserDatasRecord, JiraCredsRecord> USER_DATAS__FK_USER_DATAS_JIRA_CREDS_JIRA_CREDS_ID = ForeignKeys0.USER_DATAS__FK_USER_DATAS_JIRA_CREDS_JIRA_CREDS_ID;
    public static final ForeignKey<UserEventsRecord, UserDatasRecord> USER_EVENTS__FK_USER_EVENTS_USER_DATAS_CREATER_ID = ForeignKeys0.USER_EVENTS__FK_USER_EVENTS_USER_DATAS_CREATER_ID;
    public static final ForeignKey<UserEventsRecord, UserDatasRecord> USER_EVENTS__FK_USER_EVENTS_USER_DATAS_RECEIVER_ID = ForeignKeys0.USER_EVENTS__FK_USER_EVENTS_USER_DATAS_RECEIVER_ID;
    public static final ForeignKey<UserEventsRecord, DealsRecord> USER_EVENTS__FK_USER_EVENTS_DEALS_DEAL_ID = ForeignKeys0.USER_EVENTS__FK_USER_EVENTS_DEALS_DEAL_ID;
    public static final ForeignKey<UserEventsRecord, DealMessageRecord> USER_EVENTS__FK_USER_EVENTS_DEAL_MESSAGE_DEAL_MESSAGE_ID = ForeignKeys0.USER_EVENTS__FK_USER_EVENTS_DEAL_MESSAGE_DEAL_MESSAGE_ID;
    public static final ForeignKey<UserEventsRecord, InvoicesRecord> USER_EVENTS__FK_USER_EVENTS_INVOICES_INVOICE_ID = ForeignKeys0.USER_EVENTS__FK_USER_EVENTS_INVOICES_INVOICE_ID;
    public static final ForeignKey<UserEventsRecord, InvoicePaymentsRecord> USER_EVENTS__FK_USER_EVENTS_INVOICE_PAYMENTS_INVOICE_PAYMENT_ID = ForeignKeys0.USER_EVENTS__FK_USER_EVENTS_INVOICE_PAYMENTS_INVOICE_PAYMENT_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AdMetadataRecord, Long> IDENTITY_AD_METADATA = Internal.createIdentity(AdMetadata.AD_METADATA, AdMetadata.AD_METADATA.ID);
        public static Identity<AdMetadataSnapshotRecord, Long> IDENTITY_AD_METADATA_SNAPSHOT = Internal.createIdentity(AdMetadataSnapshot.AD_METADATA_SNAPSHOT, AdMetadataSnapshot.AD_METADATA_SNAPSHOT.KEY);
        public static Identity<AdvertisementSnapshotRecord, Long> IDENTITY_ADVERTISEMENT_SNAPSHOT = Internal.createIdentity(AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT, AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT.KEY);
        public static Identity<AdvertisementsRecord, Long> IDENTITY_ADVERTISEMENTS = Internal.createIdentity(Advertisements.ADVERTISEMENTS, Advertisements.ADVERTISEMENTS.ID);
        public static Identity<AvgPricesRecord, Integer> IDENTITY_AVG_PRICES = Internal.createIdentity(AvgPrices.AVG_PRICES, AvgPrices.AVG_PRICES.ID);
        public static Identity<BalancesRecord, Long> IDENTITY_BALANCES = Internal.createIdentity(Balances.BALANCES, Balances.BALANCES.ID);
        public static Identity<BlockedUsersRecord, Long> IDENTITY_BLOCKED_USERS = Internal.createIdentity(BlockedUsers.BLOCKED_USERS, BlockedUsers.BLOCKED_USERS.ID);
        public static Identity<ComplaintsRecord, Long> IDENTITY_COMPLAINTS = Internal.createIdentity(Complaints.COMPLAINTS, Complaints.COMPLAINTS.ID);
        public static Identity<DealMessageRecord, Long> IDENTITY_DEAL_MESSAGE = Internal.createIdentity(DealMessage.DEAL_MESSAGE, DealMessage.DEAL_MESSAGE.ID);
        public static Identity<DealsRecord, Long> IDENTITY_DEALS = Internal.createIdentity(Deals.DEALS, Deals.DEALS.ID);
        public static Identity<DisputesRecord, Long> IDENTITY_DISPUTES = Internal.createIdentity(Disputes.DISPUTES, Disputes.DISPUTES.ID);
        public static Identity<FeedbacksRecord, Long> IDENTITY_FEEDBACKS = Internal.createIdentity(Feedbacks.FEEDBACKS, Feedbacks.FEEDBACKS.ID);
        public static Identity<InAddressesRecord, Long> IDENTITY_IN_ADDRESSES = Internal.createIdentity(InAddresses.IN_ADDRESSES, InAddresses.IN_ADDRESSES.ID);
        public static Identity<InTransactionsRecord, Long> IDENTITY_IN_TRANSACTIONS = Internal.createIdentity(InTransactions.IN_TRANSACTIONS, InTransactions.IN_TRANSACTIONS.ID);
        public static Identity<InvoicePaymentsRecord, Long> IDENTITY_INVOICE_PAYMENTS = Internal.createIdentity(InvoicePayments.INVOICE_PAYMENTS, InvoicePayments.INVOICE_PAYMENTS.ID);
        public static Identity<InvoicesRecord, Long> IDENTITY_INVOICES = Internal.createIdentity(Invoices.INVOICES, Invoices.INVOICES.ID);
        public static Identity<JiraCredsRecord, Long> IDENTITY_JIRA_CREDS = Internal.createIdentity(JiraCreds.JIRA_CREDS, JiraCreds.JIRA_CREDS.ID);
        public static Identity<LastAdSearchParamsRecord, Long> IDENTITY_LAST_AD_SEARCH_PARAMS = Internal.createIdentity(LastAdSearchParams.LAST_AD_SEARCH_PARAMS, LastAdSearchParams.LAST_AD_SEARCH_PARAMS.ID);
        public static Identity<OutTransactionRequestsRecord, Long> IDENTITY_OUT_TRANSACTION_REQUESTS = Internal.createIdentity(OutTransactionRequests.OUT_TRANSACTION_REQUESTS, OutTransactionRequests.OUT_TRANSACTION_REQUESTS.ID);
        public static Identity<OutTransactionsRecord, Long> IDENTITY_OUT_TRANSACTIONS = Internal.createIdentity(OutTransactions.OUT_TRANSACTIONS, OutTransactions.OUT_TRANSACTIONS.ID);
        public static Identity<TimeTableItemSnapshotRecord, Long> IDENTITY_TIME_TABLE_ITEM_SNAPSHOT = Internal.createIdentity(TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT, TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT.KEY);
        public static Identity<TimeTablesRecord, Long> IDENTITY_TIME_TABLES = Internal.createIdentity(TimeTables.TIME_TABLES, TimeTables.TIME_TABLES.ID);
        public static Identity<TrustedUsersRecord, Long> IDENTITY_TRUSTED_USERS = Internal.createIdentity(TrustedUsers.TRUSTED_USERS, TrustedUsers.TRUSTED_USERS.ID);
        public static Identity<UserDataSnapshotRecord, Long> IDENTITY_USER_DATA_SNAPSHOT = Internal.createIdentity(UserDataSnapshot.USER_DATA_SNAPSHOT, UserDataSnapshot.USER_DATA_SNAPSHOT.KEY);
        public static Identity<UserDatasRecord, Long> IDENTITY_USER_DATAS = Internal.createIdentity(UserDatas.USER_DATAS, UserDatas.USER_DATAS.ID);
        public static Identity<UserEventsRecord, Long> IDENTITY_USER_EVENTS = Internal.createIdentity(UserEvents.USER_EVENTS, UserEvents.USER_EVENTS.ID);
        public static Identity<VariablesMetadataRecord, Integer> IDENTITY_VARIABLES_METADATA = Internal.createIdentity(VariablesMetadata.VARIABLES_METADATA, VariablesMetadata.VARIABLES_METADATA.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<__EfmigrationshistoryRecord> PK___EFMIGRATIONSHISTORY = Internal.createUniqueKey(__Efmigrationshistory.__EFMIGRATIONSHISTORY, "PK___EFMigrationsHistory", new TableField[] { __Efmigrationshistory.__EFMIGRATIONSHISTORY.MIGRATIONID }, true);
        public static final UniqueKey<AdMetadataRecord> PK_AD_METADATA = Internal.createUniqueKey(AdMetadata.AD_METADATA, "pk_ad_metadata", new TableField[] { AdMetadata.AD_METADATA.ID }, true);
        public static final UniqueKey<AdMetadataSnapshotRecord> PK_AD_METADATA_SNAPSHOT = Internal.createUniqueKey(AdMetadataSnapshot.AD_METADATA_SNAPSHOT, "pk_ad_metadata_snapshot", new TableField[] { AdMetadataSnapshot.AD_METADATA_SNAPSHOT.KEY }, true);
        public static final UniqueKey<AdvertisementSnapshotRecord> PK_ADVERTISEMENT_SNAPSHOT = Internal.createUniqueKey(AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT, "pk_advertisement_snapshot", new TableField[] { AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT.KEY }, true);
        public static final UniqueKey<AdvertisementsRecord> PK_ADVERTISEMENTS = Internal.createUniqueKey(Advertisements.ADVERTISEMENTS, "pk_advertisements", new TableField[] { Advertisements.ADVERTISEMENTS.ID }, true);
        public static final UniqueKey<AvgPricesRecord> PK_AVG_PRICES = Internal.createUniqueKey(AvgPrices.AVG_PRICES, "pk_avg_prices", new TableField[] { AvgPrices.AVG_PRICES.ID }, true);
        public static final UniqueKey<BalancesRecord> PK_BALANCES = Internal.createUniqueKey(Balances.BALANCES, "pk_balances", new TableField[] { Balances.BALANCES.ID }, true);
        public static final UniqueKey<BlockedUsersRecord> PK_BLOCKED_USERS = Internal.createUniqueKey(BlockedUsers.BLOCKED_USERS, "pk_blocked_users", new TableField[] { BlockedUsers.BLOCKED_USERS.ID }, true);
        public static final UniqueKey<BtcCoreWalletsRecord> PK_BTC_CORE_WALLETS = Internal.createUniqueKey(BtcCoreWallets.BTC_CORE_WALLETS, "pk_btc_core_wallets", new TableField[] { BtcCoreWallets.BTC_CORE_WALLETS.PRIVATE_KEY }, true);
        public static final UniqueKey<ComplaintsRecord> PK_COMPLAINTS = Internal.createUniqueKey(Complaints.COMPLAINTS, "pk_complaints", new TableField[] { Complaints.COMPLAINTS.ID }, true);
        public static final UniqueKey<CryptoExchangeVariablesRecord> PK_CRYPTO_EXCHANGE_VARIABLES = Internal.createUniqueKey(CryptoExchangeVariables.CRYPTO_EXCHANGE_VARIABLES, "pk_crypto_exchange_variables", new TableField[] { CryptoExchangeVariables.CRYPTO_EXCHANGE_VARIABLES.KEY }, true);
        public static final UniqueKey<DealMessageRecord> PK_DEAL_MESSAGE = Internal.createUniqueKey(DealMessage.DEAL_MESSAGE, "pk_deal_message", new TableField[] { DealMessage.DEAL_MESSAGE.ID }, true);
        public static final UniqueKey<DealsRecord> PK_DEALS = Internal.createUniqueKey(Deals.DEALS, "pk_deals", new TableField[] { Deals.DEALS.ID }, true);
        public static final UniqueKey<DisputesRecord> PK_DISPUTES = Internal.createUniqueKey(Disputes.DISPUTES, "pk_disputes", new TableField[] { Disputes.DISPUTES.ID }, true);
        public static final UniqueKey<FeedbacksRecord> PK_FEEDBACKS = Internal.createUniqueKey(Feedbacks.FEEDBACKS, "pk_feedbacks", new TableField[] { Feedbacks.FEEDBACKS.ID }, true);
        public static final UniqueKey<FiatExchangeVariablesRecord> PK_FIAT_EXCHANGE_VARIABLES = Internal.createUniqueKey(FiatExchangeVariables.FIAT_EXCHANGE_VARIABLES, "pk_fiat_exchange_variables", new TableField[] { FiatExchangeVariables.FIAT_EXCHANGE_VARIABLES.KEY }, true);
        public static final UniqueKey<InAddressesRecord> PK_IN_ADDRESSES = Internal.createUniqueKey(InAddresses.IN_ADDRESSES, "pk_in_addresses", new TableField[] { InAddresses.IN_ADDRESSES.ID }, true);
        public static final UniqueKey<InTransactionsRecord> PK_IN_TRANSACTIONS = Internal.createUniqueKey(InTransactions.IN_TRANSACTIONS, "pk_in_transactions", new TableField[] { InTransactions.IN_TRANSACTIONS.ID }, true);
        public static final UniqueKey<InvoicePaymentsRecord> PK_INVOICE_PAYMENTS = Internal.createUniqueKey(InvoicePayments.INVOICE_PAYMENTS, "pk_invoice_payments", new TableField[] { InvoicePayments.INVOICE_PAYMENTS.ID }, true);
        public static final UniqueKey<InvoicesRecord> PK_INVOICES = Internal.createUniqueKey(Invoices.INVOICES, "pk_invoices", new TableField[] { Invoices.INVOICES.ID }, true);
        public static final UniqueKey<JiraCredsRecord> PK_JIRA_CREDS = Internal.createUniqueKey(JiraCreds.JIRA_CREDS, "pk_jira_creds", new TableField[] { JiraCreds.JIRA_CREDS.ID }, true);
        public static final UniqueKey<LastAdSearchParamsRecord> PK_LAST_AD_SEARCH_PARAMS = Internal.createUniqueKey(LastAdSearchParams.LAST_AD_SEARCH_PARAMS, "pk_last_ad_search_params", new TableField[] { LastAdSearchParams.LAST_AD_SEARCH_PARAMS.ID }, true);
        public static final UniqueKey<OutTransactionRequestsRecord> PK_OUT_TRANSACTION_REQUESTS = Internal.createUniqueKey(OutTransactionRequests.OUT_TRANSACTION_REQUESTS, "pk_out_transaction_requests", new TableField[] { OutTransactionRequests.OUT_TRANSACTION_REQUESTS.ID }, true);
        public static final UniqueKey<OutTransactionsRecord> PK_OUT_TRANSACTIONS = Internal.createUniqueKey(OutTransactions.OUT_TRANSACTIONS, "pk_out_transactions", new TableField[] { OutTransactions.OUT_TRANSACTIONS.ID }, true);
        public static final UniqueKey<TimeTableItemSnapshotRecord> PK_TIME_TABLE_ITEM_SNAPSHOT = Internal.createUniqueKey(TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT, "pk_time_table_item_snapshot", new TableField[] { TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT.KEY }, true);
        public static final UniqueKey<TimeTablesRecord> PK_TIME_TABLES = Internal.createUniqueKey(TimeTables.TIME_TABLES, "pk_time_tables", new TableField[] { TimeTables.TIME_TABLES.ID }, true);
        public static final UniqueKey<TrustedUsersRecord> PK_TRUSTED_USERS = Internal.createUniqueKey(TrustedUsers.TRUSTED_USERS, "pk_trusted_users", new TableField[] { TrustedUsers.TRUSTED_USERS.ID }, true);
        public static final UniqueKey<UserDataSnapshotRecord> PK_USER_DATA_SNAPSHOT = Internal.createUniqueKey(UserDataSnapshot.USER_DATA_SNAPSHOT, "pk_user_data_snapshot", new TableField[] { UserDataSnapshot.USER_DATA_SNAPSHOT.KEY }, true);
        public static final UniqueKey<UserDatasRecord> PK_USER_DATAS = Internal.createUniqueKey(UserDatas.USER_DATAS, "pk_user_datas", new TableField[] { UserDatas.USER_DATAS.ID }, true);
        public static final UniqueKey<UserEventsRecord> PK_USER_EVENTS = Internal.createUniqueKey(UserEvents.USER_EVENTS, "pk_user_events", new TableField[] { UserEvents.USER_EVENTS.ID }, true);
        public static final UniqueKey<VariablesMetadataRecord> PK_VARIABLES_METADATA = Internal.createUniqueKey(VariablesMetadata.VARIABLES_METADATA, "pk_variables_metadata", new TableField[] { VariablesMetadata.VARIABLES_METADATA.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AdMetadataRecord, AdvertisementsRecord> AD_METADATA__FK_AD_METADATA_ADVERTISEMENTS_ADVERTISEMENT_ID = Internal.createForeignKey(Keys.PK_ADVERTISEMENTS, AdMetadata.AD_METADATA, "fk_ad_metadata_advertisements_advertisement_id", new TableField[] { AdMetadata.AD_METADATA.ADVERTISEMENT_ID }, true);
        public static final ForeignKey<AdvertisementSnapshotRecord, UserDataSnapshotRecord> ADVERTISEMENT_SNAPSHOT__FK_ADVERTISEMENT_SNAPSHOT_USER_DATA_SNAPSHOT_OWNER_KEY = Internal.createForeignKey(Keys.PK_USER_DATA_SNAPSHOT, AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT, "fk_advertisement_snapshot_user_data_snapshot_owner_key", new TableField[] { AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT.OWNER_KEY }, true);
        public static final ForeignKey<AdvertisementSnapshotRecord, AdMetadataSnapshotRecord> ADVERTISEMENT_SNAPSHOT__FK_ADVERTISEMENT_SNAPSHOT_AD_METADATA_SNAPSHOT_METADATA_KEY = Internal.createForeignKey(Keys.PK_AD_METADATA_SNAPSHOT, AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT, "fk_advertisement_snapshot_ad_metadata_snapshot_metadata_key", new TableField[] { AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT.METADATA_KEY }, true);
        public static final ForeignKey<AdvertisementsRecord, UserDatasRecord> ADVERTISEMENTS__FK_ADVERTISEMENTS_USER_DATAS_OWNER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, Advertisements.ADVERTISEMENTS, "fk_advertisements_user_datas_owner_id", new TableField[] { Advertisements.ADVERTISEMENTS.OWNER_ID }, true);
        public static final ForeignKey<BalancesRecord, UserDatasRecord> BALANCES__FK_BALANCES_USER_DATAS_OWNER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, Balances.BALANCES, "fk_balances_user_datas_owner_id", new TableField[] { Balances.BALANCES.OWNER_ID }, true);
        public static final ForeignKey<BlockedUsersRecord, UserDatasRecord> BLOCKED_USERS__FK_BLOCKED_USERS_USER_DATAS_OWNER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, BlockedUsers.BLOCKED_USERS, "fk_blocked_users_user_datas_owner_id", new TableField[] { BlockedUsers.BLOCKED_USERS.OWNER_ID }, true);
        public static final ForeignKey<BlockedUsersRecord, UserDatasRecord> BLOCKED_USERS__FK_BLOCKED_USERS_USER_DATAS_USER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, BlockedUsers.BLOCKED_USERS, "fk_blocked_users_user_datas_user_id", new TableField[] { BlockedUsers.BLOCKED_USERS.USER_ID }, true);
        public static final ForeignKey<DealMessageRecord, UserDatasRecord> DEAL_MESSAGE__FK_DEAL_MESSAGE_USER_DATAS_OWNER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, DealMessage.DEAL_MESSAGE, "fk_deal_message_user_datas_owner_id", new TableField[] { DealMessage.DEAL_MESSAGE.OWNER_ID }, true);
        public static final ForeignKey<DealMessageRecord, DealsRecord> DEAL_MESSAGE__FK_DEAL_MESSAGE_DEALS_DEAL_ID = Internal.createForeignKey(Keys.PK_DEALS, DealMessage.DEAL_MESSAGE, "fk_deal_message_deals_deal_id", new TableField[] { DealMessage.DEAL_MESSAGE.DEAL_ID }, true);
        public static final ForeignKey<DealsRecord, FeedbacksRecord> DEALS__FK_DEALS_FEEDBACKS_AD_OWNER_FEED_BACK_ID = Internal.createForeignKey(Keys.PK_FEEDBACKS, Deals.DEALS, "fk_deals_feedbacks_ad_owner_feed_back_id", new TableField[] { Deals.DEALS.AD_OWNER_FEED_BACK_ID }, true);
        public static final ForeignKey<DealsRecord, FeedbacksRecord> DEALS__FK_DEALS_FEEDBACKS_INITIATOR_FEEDBACK_ID = Internal.createForeignKey(Keys.PK_FEEDBACKS, Deals.DEALS, "fk_deals_feedbacks_initiator_feedback_id", new TableField[] { Deals.DEALS.INITIATOR_FEEDBACK_ID }, true);
        public static final ForeignKey<DealsRecord, DisputesRecord> DEALS__FK_DEALS_DISPUTES_DISPUTE_ID = Internal.createForeignKey(Keys.PK_DISPUTES, Deals.DEALS, "fk_deals_disputes_dispute_id", new TableField[] { Deals.DEALS.DISPUTE_ID }, true);
        public static final ForeignKey<DealsRecord, AdvertisementSnapshotRecord> DEALS__FK_DEALS_ADVERTISEMENT_SNAPSHOT_AD_SNAPSHOT_KEY = Internal.createForeignKey(Keys.PK_ADVERTISEMENT_SNAPSHOT, Deals.DEALS, "fk_deals_advertisement_snapshot_ad_snapshot_key", new TableField[] { Deals.DEALS.AD_SNAPSHOT_KEY }, true);
        public static final ForeignKey<DealsRecord, UserDataSnapshotRecord> DEALS__FK_DEALS_USER_DATA_SNAPSHOT_INITIATOR_SNAPSHOT_KEY = Internal.createForeignKey(Keys.PK_USER_DATA_SNAPSHOT, Deals.DEALS, "fk_deals_user_data_snapshot_initiator_snapshot_key", new TableField[] { Deals.DEALS.INITIATOR_SNAPSHOT_KEY }, true);
        public static final ForeignKey<FeedbacksRecord, UserDatasRecord> FEEDBACKS__FK_FEEDBACKS_USER_DATAS_FROM_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, Feedbacks.FEEDBACKS, "fk_feedbacks_user_datas_from_id", new TableField[] { Feedbacks.FEEDBACKS.FROM_ID }, true);
        public static final ForeignKey<FeedbacksRecord, UserDatasRecord> FEEDBACKS__FK_FEEDBACKS_USER_DATAS_TO_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, Feedbacks.FEEDBACKS, "fk_feedbacks_user_datas_to_id", new TableField[] { Feedbacks.FEEDBACKS.TO_ID }, true);
        public static final ForeignKey<InAddressesRecord, BtcCoreWalletsRecord> IN_ADDRESSES__FK_IN_ADDRESSES_BTC_CORE_WALLETS_BTC_CORE_WALLET_PRIVATE_KEY = Internal.createForeignKey(Keys.PK_BTC_CORE_WALLETS, InAddresses.IN_ADDRESSES, "fk_in_addresses_btc_core_wallets_btc_core_wallet_private_key", new TableField[] { InAddresses.IN_ADDRESSES.BTC_CORE_WALLET_PRIVATE_KEY }, true);
        public static final ForeignKey<InAddressesRecord, UserDatasRecord> IN_ADDRESSES__FK_IN_ADDRESSES_USER_DATAS_OWNER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, InAddresses.IN_ADDRESSES, "fk_in_addresses_user_datas_owner_id", new TableField[] { InAddresses.IN_ADDRESSES.OWNER_ID }, true);
        public static final ForeignKey<InTransactionsRecord, InAddressesRecord> IN_TRANSACTIONS__FK_IN_TRANSACTIONS_IN_ADDRESSES_ADDRESS_ID = Internal.createForeignKey(Keys.PK_IN_ADDRESSES, InTransactions.IN_TRANSACTIONS, "fk_in_transactions_in_addresses_address_id", new TableField[] { InTransactions.IN_TRANSACTIONS.ADDRESS_ID }, true);
        public static final ForeignKey<InvoicePaymentsRecord, InvoicesRecord> INVOICE_PAYMENTS__FK_INVOICE_PAYMENTS_INVOICES_INVOICE_FK = Internal.createForeignKey(Keys.PK_INVOICES, InvoicePayments.INVOICE_PAYMENTS, "fk_invoice_payments_invoices_invoice_fk", new TableField[] { InvoicePayments.INVOICE_PAYMENTS.INVOICE_FK }, true);
        public static final ForeignKey<InvoicePaymentsRecord, UserDatasRecord> INVOICE_PAYMENTS__FK_INVOICE_PAYMENTS_USER_DATAS_USER_DATA_FK = Internal.createForeignKey(Keys.PK_USER_DATAS, InvoicePayments.INVOICE_PAYMENTS, "fk_invoice_payments_user_datas_user_data_fk", new TableField[] { InvoicePayments.INVOICE_PAYMENTS.USER_DATA_FK }, true);
        public static final ForeignKey<InvoicesRecord, UserDatasRecord> INVOICES__FK_INVOICES_USER_DATAS_OWNER_FK = Internal.createForeignKey(Keys.PK_USER_DATAS, Invoices.INVOICES, "fk_invoices_user_datas_owner_fk", new TableField[] { Invoices.INVOICES.OWNER_FK }, true);
        public static final ForeignKey<InvoicesRecord, UserDatasRecord> INVOICES__FK_INVOICES_USER_DATAS_TARGET_USER_FK = Internal.createForeignKey(Keys.PK_USER_DATAS, Invoices.INVOICES, "fk_invoices_user_datas_target_user_fk", new TableField[] { Invoices.INVOICES.TARGET_USER_FK }, true);
        public static final ForeignKey<LastAdSearchParamsRecord, UserDatasRecord> LAST_AD_SEARCH_PARAMS__FK_LAST_AD_SEARCH_PARAMS_USER_DATAS_OWNER_FK = Internal.createForeignKey(Keys.PK_USER_DATAS, LastAdSearchParams.LAST_AD_SEARCH_PARAMS, "fk_last_ad_search_params_user_datas_owner_fk", new TableField[] { LastAdSearchParams.LAST_AD_SEARCH_PARAMS.OWNER_FK }, true);
        public static final ForeignKey<OutTransactionRequestsRecord, UserDatasRecord> OUT_TRANSACTION_REQUESTS__FK_OUT_TRANSACTION_REQUESTS_USER_DATAS_OWNER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, OutTransactionRequests.OUT_TRANSACTION_REQUESTS, "fk_out_transaction_requests_user_datas_owner_id", new TableField[] { OutTransactionRequests.OUT_TRANSACTION_REQUESTS.OWNER_ID }, true);
        public static final ForeignKey<OutTransactionRequestsRecord, BtcCoreWalletsRecord> OUT_TRANSACTION_REQUESTS__FK_OUT_TRANSACTION_REQUESTS_BTC_CORE_WALLETS_BTC_CORE_WALLET_P_7e = Internal.createForeignKey(Keys.PK_BTC_CORE_WALLETS, OutTransactionRequests.OUT_TRANSACTION_REQUESTS, "fk_out_transaction_requests_btc_core_wallets_btc_core_wallet_p~", new TableField[] { OutTransactionRequests.OUT_TRANSACTION_REQUESTS.BTC_CORE_WALLET_PRIVATE_KEY }, true);
        public static final ForeignKey<OutTransactionsRecord, BtcCoreWalletsRecord> OUT_TRANSACTIONS__FK_OUT_TRANSACTIONS_BTC_CORE_WALLETS_WALLET_PRIVATE_KEY = Internal.createForeignKey(Keys.PK_BTC_CORE_WALLETS, OutTransactions.OUT_TRANSACTIONS, "fk_out_transactions_btc_core_wallets_wallet_private_key", new TableField[] { OutTransactions.OUT_TRANSACTIONS.WALLET_PRIVATE_KEY }, true);
        public static final ForeignKey<OutTransactionsRecord, OutTransactionRequestsRecord> OUT_TRANSACTIONS__FK_OUT_TRANSACTIONS_OUT_TRANSACTION_REQUESTS_REQUEST_ID = Internal.createForeignKey(Keys.PK_OUT_TRANSACTION_REQUESTS, OutTransactions.OUT_TRANSACTIONS, "fk_out_transactions_out_transaction_requests_request_id", new TableField[] { OutTransactions.OUT_TRANSACTIONS.REQUEST_ID }, true);
        public static final ForeignKey<TimeTableItemSnapshotRecord, AdvertisementSnapshotRecord> TIME_TABLE_ITEM_SNAPSHOT__FK_TIME_TABLE_ITEM_SNAPSHOT_ADVERTISEMENT_SNAPSHOT_ADVERTISEME_7e = Internal.createForeignKey(Keys.PK_ADVERTISEMENT_SNAPSHOT, TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT, "fk_time_table_item_snapshot_advertisement_snapshot_advertiseme~", new TableField[] { TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT.ADVERTISEMENT_SNAPSHOT_KEY }, true);
        public static final ForeignKey<TimeTablesRecord, AdvertisementsRecord> TIME_TABLES__FK_TIME_TABLES_ADVERTISEMENTS_ADVERTISEMENT_ID = Internal.createForeignKey(Keys.PK_ADVERTISEMENTS, TimeTables.TIME_TABLES, "fk_time_tables_advertisements_advertisement_id", new TableField[] { TimeTables.TIME_TABLES.ADVERTISEMENT_ID }, true);
        public static final ForeignKey<TrustedUsersRecord, UserDatasRecord> TRUSTED_USERS__FK_TRUSTED_USERS_USER_DATAS_OWNER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, TrustedUsers.TRUSTED_USERS, "fk_trusted_users_user_datas_owner_id", new TableField[] { TrustedUsers.TRUSTED_USERS.OWNER_ID }, true);
        public static final ForeignKey<TrustedUsersRecord, UserDatasRecord> TRUSTED_USERS__FK_TRUSTED_USERS_USER_DATAS_USER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, TrustedUsers.TRUSTED_USERS, "fk_trusted_users_user_datas_user_id", new TableField[] { TrustedUsers.TRUSTED_USERS.USER_ID }, true);
        public static final ForeignKey<UserDatasRecord, JiraCredsRecord> USER_DATAS__FK_USER_DATAS_JIRA_CREDS_JIRA_CREDS_ID = Internal.createForeignKey(Keys.PK_JIRA_CREDS, UserDatas.USER_DATAS, "fk_user_datas_jira_creds_jira_creds_id", new TableField[] { UserDatas.USER_DATAS.JIRA_CREDS_ID }, true);
        public static final ForeignKey<UserEventsRecord, UserDatasRecord> USER_EVENTS__FK_USER_EVENTS_USER_DATAS_CREATER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, UserEvents.USER_EVENTS, "fk_user_events_user_datas_creater_id", new TableField[] { UserEvents.USER_EVENTS.CREATER_ID }, true);
        public static final ForeignKey<UserEventsRecord, UserDatasRecord> USER_EVENTS__FK_USER_EVENTS_USER_DATAS_RECEIVER_ID = Internal.createForeignKey(Keys.PK_USER_DATAS, UserEvents.USER_EVENTS, "fk_user_events_user_datas_receiver_id", new TableField[] { UserEvents.USER_EVENTS.RECEIVER_ID }, true);
        public static final ForeignKey<UserEventsRecord, DealsRecord> USER_EVENTS__FK_USER_EVENTS_DEALS_DEAL_ID = Internal.createForeignKey(Keys.PK_DEALS, UserEvents.USER_EVENTS, "fk_user_events_deals_deal_id", new TableField[] { UserEvents.USER_EVENTS.DEAL_ID }, true);
        public static final ForeignKey<UserEventsRecord, DealMessageRecord> USER_EVENTS__FK_USER_EVENTS_DEAL_MESSAGE_DEAL_MESSAGE_ID = Internal.createForeignKey(Keys.PK_DEAL_MESSAGE, UserEvents.USER_EVENTS, "fk_user_events_deal_message_deal_message_id", new TableField[] { UserEvents.USER_EVENTS.DEAL_MESSAGE_ID }, true);
        public static final ForeignKey<UserEventsRecord, InvoicesRecord> USER_EVENTS__FK_USER_EVENTS_INVOICES_INVOICE_ID = Internal.createForeignKey(Keys.PK_INVOICES, UserEvents.USER_EVENTS, "fk_user_events_invoices_invoice_id", new TableField[] { UserEvents.USER_EVENTS.INVOICE_ID }, true);
        public static final ForeignKey<UserEventsRecord, InvoicePaymentsRecord> USER_EVENTS__FK_USER_EVENTS_INVOICE_PAYMENTS_INVOICE_PAYMENT_ID = Internal.createForeignKey(Keys.PK_INVOICE_PAYMENTS, UserEvents.USER_EVENTS, "fk_user_events_invoice_payments_invoice_payment_id", new TableField[] { UserEvents.USER_EVENTS.INVOICE_PAYMENT_ID }, true);
    }
}
