/*
 * This file is generated by jOOQ.
 */
package ru.toxic.db.data;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.toxic.db.data.tables.AdMetadata;
import ru.toxic.db.data.tables.AdMetadataSnapshot;
import ru.toxic.db.data.tables.AdvertisementSnapshot;
import ru.toxic.db.data.tables.Advertisements;
import ru.toxic.db.data.tables.AvgPrices;
import ru.toxic.db.data.tables.Balances;
import ru.toxic.db.data.tables.BlockedUsers;
import ru.toxic.db.data.tables.BtcCoreWallets;
import ru.toxic.db.data.tables.Complaints;
import ru.toxic.db.data.tables.CryptoExchangeVariables;
import ru.toxic.db.data.tables.DealMessage;
import ru.toxic.db.data.tables.Deals;
import ru.toxic.db.data.tables.Disputes;
import ru.toxic.db.data.tables.Feedbacks;
import ru.toxic.db.data.tables.FiatExchangeVariables;
import ru.toxic.db.data.tables.InAddresses;
import ru.toxic.db.data.tables.InTransactions;
import ru.toxic.db.data.tables.InvoicePayments;
import ru.toxic.db.data.tables.Invoices;
import ru.toxic.db.data.tables.JiraCreds;
import ru.toxic.db.data.tables.LastAdSearchParams;
import ru.toxic.db.data.tables.OutTransactionRequests;
import ru.toxic.db.data.tables.OutTransactions;
import ru.toxic.db.data.tables.TimeTableItemSnapshot;
import ru.toxic.db.data.tables.TimeTables;
import ru.toxic.db.data.tables.TrustedUsers;
import ru.toxic.db.data.tables.UserDataSnapshot;
import ru.toxic.db.data.tables.UserDatas;
import ru.toxic.db.data.tables.UserEvents;
import ru.toxic.db.data.tables.VariablesMetadata;
import ru.toxic.db.data.tables.__Efmigrationshistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1453813410;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.__EFMigrationsHistory</code>.
     */
    public final __Efmigrationshistory __EFMIGRATIONSHISTORY = __Efmigrationshistory.__EFMIGRATIONSHISTORY;

    /**
     * The table <code>public.ad_metadata</code>.
     */
    public final AdMetadata AD_METADATA = AdMetadata.AD_METADATA;

    /**
     * The table <code>public.ad_metadata_snapshot</code>.
     */
    public final AdMetadataSnapshot AD_METADATA_SNAPSHOT = AdMetadataSnapshot.AD_METADATA_SNAPSHOT;

    /**
     * The table <code>public.advertisement_snapshot</code>.
     */
    public final AdvertisementSnapshot ADVERTISEMENT_SNAPSHOT = AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT;

    /**
     * The table <code>public.advertisements</code>.
     */
    public final Advertisements ADVERTISEMENTS = Advertisements.ADVERTISEMENTS;

    /**
     * The table <code>public.avg_prices</code>.
     */
    public final AvgPrices AVG_PRICES = AvgPrices.AVG_PRICES;

    /**
     * The table <code>public.balances</code>.
     */
    public final Balances BALANCES = Balances.BALANCES;

    /**
     * The table <code>public.blocked_users</code>.
     */
    public final BlockedUsers BLOCKED_USERS = BlockedUsers.BLOCKED_USERS;

    /**
     * The table <code>public.btc_core_wallets</code>.
     */
    public final BtcCoreWallets BTC_CORE_WALLETS = BtcCoreWallets.BTC_CORE_WALLETS;

    /**
     * The table <code>public.complaints</code>.
     */
    public final Complaints COMPLAINTS = Complaints.COMPLAINTS;

    /**
     * The table <code>public.crypto_exchange_variables</code>.
     */
    public final CryptoExchangeVariables CRYPTO_EXCHANGE_VARIABLES = CryptoExchangeVariables.CRYPTO_EXCHANGE_VARIABLES;

    /**
     * The table <code>public.deal_message</code>.
     */
    public final DealMessage DEAL_MESSAGE = DealMessage.DEAL_MESSAGE;

    /**
     * The table <code>public.deals</code>.
     */
    public final Deals DEALS = Deals.DEALS;

    /**
     * The table <code>public.disputes</code>.
     */
    public final Disputes DISPUTES = Disputes.DISPUTES;

    /**
     * The table <code>public.feedbacks</code>.
     */
    public final Feedbacks FEEDBACKS = Feedbacks.FEEDBACKS;

    /**
     * The table <code>public.fiat_exchange_variables</code>.
     */
    public final FiatExchangeVariables FIAT_EXCHANGE_VARIABLES = FiatExchangeVariables.FIAT_EXCHANGE_VARIABLES;

    /**
     * The table <code>public.in_addresses</code>.
     */
    public final InAddresses IN_ADDRESSES = InAddresses.IN_ADDRESSES;

    /**
     * The table <code>public.in_transactions</code>.
     */
    public final InTransactions IN_TRANSACTIONS = InTransactions.IN_TRANSACTIONS;

    /**
     * The table <code>public.invoice_payments</code>.
     */
    public final InvoicePayments INVOICE_PAYMENTS = InvoicePayments.INVOICE_PAYMENTS;

    /**
     * The table <code>public.invoices</code>.
     */
    public final Invoices INVOICES = Invoices.INVOICES;

    /**
     * The table <code>public.jira_creds</code>.
     */
    public final JiraCreds JIRA_CREDS = JiraCreds.JIRA_CREDS;

    /**
     * The table <code>public.last_ad_search_params</code>.
     */
    public final LastAdSearchParams LAST_AD_SEARCH_PARAMS = LastAdSearchParams.LAST_AD_SEARCH_PARAMS;

    /**
     * The table <code>public.out_transaction_requests</code>.
     */
    public final OutTransactionRequests OUT_TRANSACTION_REQUESTS = OutTransactionRequests.OUT_TRANSACTION_REQUESTS;

    /**
     * The table <code>public.out_transactions</code>.
     */
    public final OutTransactions OUT_TRANSACTIONS = OutTransactions.OUT_TRANSACTIONS;

    /**
     * The table <code>public.time_table_item_snapshot</code>.
     */
    public final TimeTableItemSnapshot TIME_TABLE_ITEM_SNAPSHOT = TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT;

    /**
     * The table <code>public.time_tables</code>.
     */
    public final TimeTables TIME_TABLES = TimeTables.TIME_TABLES;

    /**
     * The table <code>public.trusted_users</code>.
     */
    public final TrustedUsers TRUSTED_USERS = TrustedUsers.TRUSTED_USERS;

    /**
     * The table <code>public.user_data_snapshot</code>.
     */
    public final UserDataSnapshot USER_DATA_SNAPSHOT = UserDataSnapshot.USER_DATA_SNAPSHOT;

    /**
     * The table <code>public.user_datas</code>.
     */
    public final UserDatas USER_DATAS = UserDatas.USER_DATAS;

    /**
     * The table <code>public.user_events</code>.
     */
    public final UserEvents USER_EVENTS = UserEvents.USER_EVENTS;

    /**
     * The table <code>public.variables_metadata</code>.
     */
    public final VariablesMetadata VARIABLES_METADATA = VariablesMetadata.VARIABLES_METADATA;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            __Efmigrationshistory.__EFMIGRATIONSHISTORY,
            AdMetadata.AD_METADATA,
            AdMetadataSnapshot.AD_METADATA_SNAPSHOT,
            AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT,
            Advertisements.ADVERTISEMENTS,
            AvgPrices.AVG_PRICES,
            Balances.BALANCES,
            BlockedUsers.BLOCKED_USERS,
            BtcCoreWallets.BTC_CORE_WALLETS,
            Complaints.COMPLAINTS,
            CryptoExchangeVariables.CRYPTO_EXCHANGE_VARIABLES,
            DealMessage.DEAL_MESSAGE,
            Deals.DEALS,
            Disputes.DISPUTES,
            Feedbacks.FEEDBACKS,
            FiatExchangeVariables.FIAT_EXCHANGE_VARIABLES,
            InAddresses.IN_ADDRESSES,
            InTransactions.IN_TRANSACTIONS,
            InvoicePayments.INVOICE_PAYMENTS,
            Invoices.INVOICES,
            JiraCreds.JIRA_CREDS,
            LastAdSearchParams.LAST_AD_SEARCH_PARAMS,
            OutTransactionRequests.OUT_TRANSACTION_REQUESTS,
            OutTransactions.OUT_TRANSACTIONS,
            TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT,
            TimeTables.TIME_TABLES,
            TrustedUsers.TRUSTED_USERS,
            UserDataSnapshot.USER_DATA_SNAPSHOT,
            UserDatas.USER_DATAS,
            UserEvents.USER_EVENTS,
            VariablesMetadata.VARIABLES_METADATA);
    }
}
