/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data;


import is.toxic.db.data.tables.AdMetadata;
import is.toxic.db.data.tables.AdMetadataSnapshot;
import is.toxic.db.data.tables.AdvertisementSnapshot;
import is.toxic.db.data.tables.Advertisements;
import is.toxic.db.data.tables.AvgPrices;
import is.toxic.db.data.tables.Balances;
import is.toxic.db.data.tables.BlockedUsers;
import is.toxic.db.data.tables.BtcCoreWallets;
import is.toxic.db.data.tables.Complaints;
import is.toxic.db.data.tables.CryptoExchangeVariables;
import is.toxic.db.data.tables.DealMessage;
import is.toxic.db.data.tables.Deals;
import is.toxic.db.data.tables.Disputes;
import is.toxic.db.data.tables.Feedbacks;
import is.toxic.db.data.tables.FiatExchangeVariables;
import is.toxic.db.data.tables.InAddresses;
import is.toxic.db.data.tables.InTransactions;
import is.toxic.db.data.tables.InvoicePayments;
import is.toxic.db.data.tables.Invoices;
import is.toxic.db.data.tables.JiraCreds;
import is.toxic.db.data.tables.LastAdSearchParams;
import is.toxic.db.data.tables.OutTransactionRequests;
import is.toxic.db.data.tables.OutTransactions;
import is.toxic.db.data.tables.TimeTableItemSnapshot;
import is.toxic.db.data.tables.TimeTables;
import is.toxic.db.data.tables.TrustedUsers;
import is.toxic.db.data.tables.UserDataSnapshot;
import is.toxic.db.data.tables.UserDatas;
import is.toxic.db.data.tables.UserEvents;
import is.toxic.db.data.tables.VariablesMetadata;
import is.toxic.db.data.tables.__Efmigrationshistory;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.__EFMigrationsHistory</code>.
     */
    public static final __Efmigrationshistory __EFMIGRATIONSHISTORY = __Efmigrationshistory.__EFMIGRATIONSHISTORY;

    /**
     * The table <code>public.ad_metadata</code>.
     */
    public static final AdMetadata AD_METADATA = AdMetadata.AD_METADATA;

    /**
     * The table <code>public.ad_metadata_snapshot</code>.
     */
    public static final AdMetadataSnapshot AD_METADATA_SNAPSHOT = AdMetadataSnapshot.AD_METADATA_SNAPSHOT;

    /**
     * The table <code>public.advertisement_snapshot</code>.
     */
    public static final AdvertisementSnapshot ADVERTISEMENT_SNAPSHOT = AdvertisementSnapshot.ADVERTISEMENT_SNAPSHOT;

    /**
     * The table <code>public.advertisements</code>.
     */
    public static final Advertisements ADVERTISEMENTS = Advertisements.ADVERTISEMENTS;

    /**
     * The table <code>public.avg_prices</code>.
     */
    public static final AvgPrices AVG_PRICES = AvgPrices.AVG_PRICES;

    /**
     * The table <code>public.balances</code>.
     */
    public static final Balances BALANCES = Balances.BALANCES;

    /**
     * The table <code>public.blocked_users</code>.
     */
    public static final BlockedUsers BLOCKED_USERS = BlockedUsers.BLOCKED_USERS;

    /**
     * The table <code>public.btc_core_wallets</code>.
     */
    public static final BtcCoreWallets BTC_CORE_WALLETS = BtcCoreWallets.BTC_CORE_WALLETS;

    /**
     * The table <code>public.complaints</code>.
     */
    public static final Complaints COMPLAINTS = Complaints.COMPLAINTS;

    /**
     * The table <code>public.crypto_exchange_variables</code>.
     */
    public static final CryptoExchangeVariables CRYPTO_EXCHANGE_VARIABLES = CryptoExchangeVariables.CRYPTO_EXCHANGE_VARIABLES;

    /**
     * The table <code>public.deal_message</code>.
     */
    public static final DealMessage DEAL_MESSAGE = DealMessage.DEAL_MESSAGE;

    /**
     * The table <code>public.deals</code>.
     */
    public static final Deals DEALS = Deals.DEALS;

    /**
     * The table <code>public.disputes</code>.
     */
    public static final Disputes DISPUTES = Disputes.DISPUTES;

    /**
     * The table <code>public.feedbacks</code>.
     */
    public static final Feedbacks FEEDBACKS = Feedbacks.FEEDBACKS;

    /**
     * The table <code>public.fiat_exchange_variables</code>.
     */
    public static final FiatExchangeVariables FIAT_EXCHANGE_VARIABLES = FiatExchangeVariables.FIAT_EXCHANGE_VARIABLES;

    /**
     * The table <code>public.in_addresses</code>.
     */
    public static final InAddresses IN_ADDRESSES = InAddresses.IN_ADDRESSES;

    /**
     * The table <code>public.in_transactions</code>.
     */
    public static final InTransactions IN_TRANSACTIONS = InTransactions.IN_TRANSACTIONS;

    /**
     * The table <code>public.invoice_payments</code>.
     */
    public static final InvoicePayments INVOICE_PAYMENTS = InvoicePayments.INVOICE_PAYMENTS;

    /**
     * The table <code>public.invoices</code>.
     */
    public static final Invoices INVOICES = Invoices.INVOICES;

    /**
     * The table <code>public.jira_creds</code>.
     */
    public static final JiraCreds JIRA_CREDS = JiraCreds.JIRA_CREDS;

    /**
     * The table <code>public.last_ad_search_params</code>.
     */
    public static final LastAdSearchParams LAST_AD_SEARCH_PARAMS = LastAdSearchParams.LAST_AD_SEARCH_PARAMS;

    /**
     * The table <code>public.out_transaction_requests</code>.
     */
    public static final OutTransactionRequests OUT_TRANSACTION_REQUESTS = OutTransactionRequests.OUT_TRANSACTION_REQUESTS;

    /**
     * The table <code>public.out_transactions</code>.
     */
    public static final OutTransactions OUT_TRANSACTIONS = OutTransactions.OUT_TRANSACTIONS;

    /**
     * The table <code>public.time_table_item_snapshot</code>.
     */
    public static final TimeTableItemSnapshot TIME_TABLE_ITEM_SNAPSHOT = TimeTableItemSnapshot.TIME_TABLE_ITEM_SNAPSHOT;

    /**
     * The table <code>public.time_tables</code>.
     */
    public static final TimeTables TIME_TABLES = TimeTables.TIME_TABLES;

    /**
     * The table <code>public.trusted_users</code>.
     */
    public static final TrustedUsers TRUSTED_USERS = TrustedUsers.TRUSTED_USERS;

    /**
     * The table <code>public.user_data_snapshot</code>.
     */
    public static final UserDataSnapshot USER_DATA_SNAPSHOT = UserDataSnapshot.USER_DATA_SNAPSHOT;

    /**
     * The table <code>public.user_datas</code>.
     */
    public static final UserDatas USER_DATAS = UserDatas.USER_DATAS;

    /**
     * The table <code>public.user_events</code>.
     */
    public static final UserEvents USER_EVENTS = UserEvents.USER_EVENTS;

    /**
     * The table <code>public.variables_metadata</code>.
     */
    public static final VariablesMetadata VARIABLES_METADATA = VariablesMetadata.VARIABLES_METADATA;
}
