/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import is.toxic.db.data.tables.AdMetadata;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdMetadataRecord extends UpdatableRecordImpl<AdMetadataRecord> implements Record5<Long, Integer, BigDecimal, BigDecimal, Long> {

    private static final long serialVersionUID = -1699944021;

    /**
     * Setter for <code>public.ad_metadata.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ad_metadata.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ad_metadata.status</code>.
     */
    public void setStatus(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ad_metadata.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.ad_metadata.max_amount</code>.
     */
    public void setMaxAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ad_metadata.max_amount</code>.
     */
    public BigDecimal getMaxAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.ad_metadata.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ad_metadata.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.ad_metadata.advertisement_id</code>.
     */
    public void setAdvertisementId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ad_metadata.advertisement_id</code>.
     */
    public Long getAdvertisementId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Integer, BigDecimal, BigDecimal, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Integer, BigDecimal, BigDecimal, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AdMetadata.AD_METADATA.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AdMetadata.AD_METADATA.STATUS;
    }

    @Override
    public Field<BigDecimal> field3() {
        return AdMetadata.AD_METADATA.MAX_AMOUNT;
    }

    @Override
    public Field<BigDecimal> field4() {
        return AdMetadata.AD_METADATA.PRICE;
    }

    @Override
    public Field<Long> field5() {
        return AdMetadata.AD_METADATA.ADVERTISEMENT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getStatus();
    }

    @Override
    public BigDecimal component3() {
        return getMaxAmount();
    }

    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    @Override
    public Long component5() {
        return getAdvertisementId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getStatus();
    }

    @Override
    public BigDecimal value3() {
        return getMaxAmount();
    }

    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    @Override
    public Long value5() {
        return getAdvertisementId();
    }

    @Override
    public AdMetadataRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AdMetadataRecord value2(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public AdMetadataRecord value3(BigDecimal value) {
        setMaxAmount(value);
        return this;
    }

    @Override
    public AdMetadataRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public AdMetadataRecord value5(Long value) {
        setAdvertisementId(value);
        return this;
    }

    @Override
    public AdMetadataRecord values(Long value1, Integer value2, BigDecimal value3, BigDecimal value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdMetadataRecord
     */
    public AdMetadataRecord() {
        super(AdMetadata.AD_METADATA);
    }

    /**
     * Create a detached, initialised AdMetadataRecord
     */
    public AdMetadataRecord(Long id, Integer status, BigDecimal maxAmount, BigDecimal price, Long advertisementId) {
        super(AdMetadata.AD_METADATA);

        set(0, id);
        set(1, status);
        set(2, maxAmount);
        set(3, price);
        set(4, advertisementId);
    }
}
