/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import is.toxic.db.data.tables.AdMetadataSnapshot;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdMetadataSnapshotRecord extends UpdatableRecordImpl<AdMetadataSnapshotRecord> implements Record4<Long, Integer, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1539420652;

    /**
     * Setter for <code>public.ad_metadata_snapshot.key</code>.
     */
    public void setKey(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ad_metadata_snapshot.key</code>.
     */
    public Long getKey() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ad_metadata_snapshot.status</code>.
     */
    public void setStatus(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ad_metadata_snapshot.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.ad_metadata_snapshot.max_amount</code>.
     */
    public void setMaxAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ad_metadata_snapshot.max_amount</code>.
     */
    public BigDecimal getMaxAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.ad_metadata_snapshot.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ad_metadata_snapshot.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, BigDecimal, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Integer, BigDecimal, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AdMetadataSnapshot.AD_METADATA_SNAPSHOT.KEY;
    }

    @Override
    public Field<Integer> field2() {
        return AdMetadataSnapshot.AD_METADATA_SNAPSHOT.STATUS;
    }

    @Override
    public Field<BigDecimal> field3() {
        return AdMetadataSnapshot.AD_METADATA_SNAPSHOT.MAX_AMOUNT;
    }

    @Override
    public Field<BigDecimal> field4() {
        return AdMetadataSnapshot.AD_METADATA_SNAPSHOT.PRICE;
    }

    @Override
    public Long component1() {
        return getKey();
    }

    @Override
    public Integer component2() {
        return getStatus();
    }

    @Override
    public BigDecimal component3() {
        return getMaxAmount();
    }

    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    @Override
    public Long value1() {
        return getKey();
    }

    @Override
    public Integer value2() {
        return getStatus();
    }

    @Override
    public BigDecimal value3() {
        return getMaxAmount();
    }

    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    @Override
    public AdMetadataSnapshotRecord value1(Long value) {
        setKey(value);
        return this;
    }

    @Override
    public AdMetadataSnapshotRecord value2(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public AdMetadataSnapshotRecord value3(BigDecimal value) {
        setMaxAmount(value);
        return this;
    }

    @Override
    public AdMetadataSnapshotRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public AdMetadataSnapshotRecord values(Long value1, Integer value2, BigDecimal value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdMetadataSnapshotRecord
     */
    public AdMetadataSnapshotRecord() {
        super(AdMetadataSnapshot.AD_METADATA_SNAPSHOT);
    }

    /**
     * Create a detached, initialised AdMetadataSnapshotRecord
     */
    public AdMetadataSnapshotRecord(Long key, Integer status, BigDecimal maxAmount, BigDecimal price) {
        super(AdMetadataSnapshot.AD_METADATA_SNAPSHOT);

        set(0, key);
        set(1, status);
        set(2, maxAmount);
        set(3, price);
    }
}
