/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables.records;


import is.toxic.db.data.tables.Advertisements;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdvertisementsRecord extends UpdatableRecordImpl<AdvertisementsRecord> implements Record19<Long, String, BigDecimal, BigDecimal, String, LocalDateTime, Integer, Integer, Integer, Integer, Boolean, Long, Boolean, Boolean, Boolean, Boolean, String, Long, Boolean> {

    private static final long serialVersionUID = 677302084;

    /**
     * Setter for <code>public.advertisements.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.advertisements.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.advertisements.equation</code>.
     */
    public void setEquation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.advertisements.equation</code>.
     */
    public String getEquation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.advertisements.min_amount</code>.
     */
    public void setMinAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.advertisements.min_amount</code>.
     */
    public BigDecimal getMinAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.advertisements.max_amount</code>.
     */
    public void setMaxAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.advertisements.max_amount</code>.
     */
    public BigDecimal getMaxAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.advertisements.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.advertisements.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.advertisements.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.advertisements.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.advertisements.country</code>.
     */
    public void setCountry(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.advertisements.country</code>.
     */
    public Integer getCountry() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.advertisements.payment_type</code>.
     */
    public void setPaymentType(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.advertisements.payment_type</code>.
     */
    public Integer getPaymentType() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.advertisements.fiat_currency</code>.
     */
    public void setFiatCurrency(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.advertisements.fiat_currency</code>.
     */
    public Integer getFiatCurrency() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.advertisements.crypto_currency</code>.
     */
    public void setCryptoCurrency(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.advertisements.crypto_currency</code>.
     */
    public Integer getCryptoCurrency() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.advertisements.is_buy</code>.
     */
    public void setIsBuy(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.advertisements.is_buy</code>.
     */
    public Boolean getIsBuy() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.advertisements.owner_id</code>.
     */
    public void setOwnerId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.advertisements.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.advertisements.monitor_liquidity</code>.
     */
    public void setMonitorLiquidity(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.advertisements.monitor_liquidity</code>.
     */
    public Boolean getMonitorLiquidity() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.advertisements.not_anonymous</code>.
     */
    public void setNotAnonymous(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.advertisements.not_anonymous</code>.
     */
    public Boolean getNotAnonymous() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.advertisements.phone_confirmed</code>.
     */
    public void setPhoneConfirmed(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.advertisements.phone_confirmed</code>.
     */
    public Boolean getPhoneConfirmed() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.advertisements.trusted</code>.
     */
    public void setTrusted(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.advertisements.trusted</code>.
     */
    public Boolean getTrusted() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>public.advertisements.title</code>.
     */
    public void setTitle(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.advertisements.title</code>.
     */
    public String getTitle() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.advertisements.window</code>.
     */
    public void setWindow(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.advertisements.window</code>.
     */
    public Long getWindow() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.advertisements.is_enabled</code>.
     */
    public void setIsEnabled(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.advertisements.is_enabled</code>.
     */
    public Boolean getIsEnabled() {
        return (Boolean) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, String, BigDecimal, BigDecimal, String, LocalDateTime, Integer, Integer, Integer, Integer, Boolean, Long, Boolean, Boolean, Boolean, Boolean, String, Long, Boolean> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, String, BigDecimal, BigDecimal, String, LocalDateTime, Integer, Integer, Integer, Integer, Boolean, Long, Boolean, Boolean, Boolean, Boolean, String, Long, Boolean> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Advertisements.ADVERTISEMENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Advertisements.ADVERTISEMENTS.EQUATION;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Advertisements.ADVERTISEMENTS.MIN_AMOUNT;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Advertisements.ADVERTISEMENTS.MAX_AMOUNT;
    }

    @Override
    public Field<String> field5() {
        return Advertisements.ADVERTISEMENTS.MESSAGE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Advertisements.ADVERTISEMENTS.CREATED_AT;
    }

    @Override
    public Field<Integer> field7() {
        return Advertisements.ADVERTISEMENTS.COUNTRY;
    }

    @Override
    public Field<Integer> field8() {
        return Advertisements.ADVERTISEMENTS.PAYMENT_TYPE;
    }

    @Override
    public Field<Integer> field9() {
        return Advertisements.ADVERTISEMENTS.FIAT_CURRENCY;
    }

    @Override
    public Field<Integer> field10() {
        return Advertisements.ADVERTISEMENTS.CRYPTO_CURRENCY;
    }

    @Override
    public Field<Boolean> field11() {
        return Advertisements.ADVERTISEMENTS.IS_BUY;
    }

    @Override
    public Field<Long> field12() {
        return Advertisements.ADVERTISEMENTS.OWNER_ID;
    }

    @Override
    public Field<Boolean> field13() {
        return Advertisements.ADVERTISEMENTS.MONITOR_LIQUIDITY;
    }

    @Override
    public Field<Boolean> field14() {
        return Advertisements.ADVERTISEMENTS.NOT_ANONYMOUS;
    }

    @Override
    public Field<Boolean> field15() {
        return Advertisements.ADVERTISEMENTS.PHONE_CONFIRMED;
    }

    @Override
    public Field<Boolean> field16() {
        return Advertisements.ADVERTISEMENTS.TRUSTED;
    }

    @Override
    public Field<String> field17() {
        return Advertisements.ADVERTISEMENTS.TITLE;
    }

    @Override
    public Field<Long> field18() {
        return Advertisements.ADVERTISEMENTS.WINDOW;
    }

    @Override
    public Field<Boolean> field19() {
        return Advertisements.ADVERTISEMENTS.IS_ENABLED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEquation();
    }

    @Override
    public BigDecimal component3() {
        return getMinAmount();
    }

    @Override
    public BigDecimal component4() {
        return getMaxAmount();
    }

    @Override
    public String component5() {
        return getMessage();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public Integer component7() {
        return getCountry();
    }

    @Override
    public Integer component8() {
        return getPaymentType();
    }

    @Override
    public Integer component9() {
        return getFiatCurrency();
    }

    @Override
    public Integer component10() {
        return getCryptoCurrency();
    }

    @Override
    public Boolean component11() {
        return getIsBuy();
    }

    @Override
    public Long component12() {
        return getOwnerId();
    }

    @Override
    public Boolean component13() {
        return getMonitorLiquidity();
    }

    @Override
    public Boolean component14() {
        return getNotAnonymous();
    }

    @Override
    public Boolean component15() {
        return getPhoneConfirmed();
    }

    @Override
    public Boolean component16() {
        return getTrusted();
    }

    @Override
    public String component17() {
        return getTitle();
    }

    @Override
    public Long component18() {
        return getWindow();
    }

    @Override
    public Boolean component19() {
        return getIsEnabled();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEquation();
    }

    @Override
    public BigDecimal value3() {
        return getMinAmount();
    }

    @Override
    public BigDecimal value4() {
        return getMaxAmount();
    }

    @Override
    public String value5() {
        return getMessage();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public Integer value7() {
        return getCountry();
    }

    @Override
    public Integer value8() {
        return getPaymentType();
    }

    @Override
    public Integer value9() {
        return getFiatCurrency();
    }

    @Override
    public Integer value10() {
        return getCryptoCurrency();
    }

    @Override
    public Boolean value11() {
        return getIsBuy();
    }

    @Override
    public Long value12() {
        return getOwnerId();
    }

    @Override
    public Boolean value13() {
        return getMonitorLiquidity();
    }

    @Override
    public Boolean value14() {
        return getNotAnonymous();
    }

    @Override
    public Boolean value15() {
        return getPhoneConfirmed();
    }

    @Override
    public Boolean value16() {
        return getTrusted();
    }

    @Override
    public String value17() {
        return getTitle();
    }

    @Override
    public Long value18() {
        return getWindow();
    }

    @Override
    public Boolean value19() {
        return getIsEnabled();
    }

    @Override
    public AdvertisementsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value2(String value) {
        setEquation(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value3(BigDecimal value) {
        setMinAmount(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value4(BigDecimal value) {
        setMaxAmount(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value5(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value7(Integer value) {
        setCountry(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value8(Integer value) {
        setPaymentType(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value9(Integer value) {
        setFiatCurrency(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value10(Integer value) {
        setCryptoCurrency(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value11(Boolean value) {
        setIsBuy(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value12(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value13(Boolean value) {
        setMonitorLiquidity(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value14(Boolean value) {
        setNotAnonymous(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value15(Boolean value) {
        setPhoneConfirmed(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value16(Boolean value) {
        setTrusted(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value17(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value18(Long value) {
        setWindow(value);
        return this;
    }

    @Override
    public AdvertisementsRecord value19(Boolean value) {
        setIsEnabled(value);
        return this;
    }

    @Override
    public AdvertisementsRecord values(Long value1, String value2, BigDecimal value3, BigDecimal value4, String value5, LocalDateTime value6, Integer value7, Integer value8, Integer value9, Integer value10, Boolean value11, Long value12, Boolean value13, Boolean value14, Boolean value15, Boolean value16, String value17, Long value18, Boolean value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdvertisementsRecord
     */
    public AdvertisementsRecord() {
        super(Advertisements.ADVERTISEMENTS);
    }

    /**
     * Create a detached, initialised AdvertisementsRecord
     */
    public AdvertisementsRecord(Long id, String equation, BigDecimal minAmount, BigDecimal maxAmount, String message, LocalDateTime createdAt, Integer country, Integer paymentType, Integer fiatCurrency, Integer cryptoCurrency, Boolean isBuy, Long ownerId, Boolean monitorLiquidity, Boolean notAnonymous, Boolean phoneConfirmed, Boolean trusted, String title, Long window, Boolean isEnabled) {
        super(Advertisements.ADVERTISEMENTS);

        set(0, id);
        set(1, equation);
        set(2, minAmount);
        set(3, maxAmount);
        set(4, message);
        set(5, createdAt);
        set(6, country);
        set(7, paymentType);
        set(8, fiatCurrency);
        set(9, cryptoCurrency);
        set(10, isBuy);
        set(11, ownerId);
        set(12, monitorLiquidity);
        set(13, notAnonymous);
        set(14, phoneConfirmed);
        set(15, trusted);
        set(16, title);
        set(17, window);
        set(18, isEnabled);
    }
}
