/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import is.toxic.db.data.tables.InAddresses;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InAddressesRecord extends UpdatableRecordImpl<InAddressesRecord> implements Record5<Long, String, String, Long, Boolean> {

    private static final long serialVersionUID = -138291677;

    /**
     * Setter for <code>public.in_addresses.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.in_addresses.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.in_addresses.address</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.in_addresses.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.in_addresses.btc_core_wallet_private_key</code>.
     */
    public void setBtcCoreWalletPrivateKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.in_addresses.btc_core_wallet_private_key</code>.
     */
    public String getBtcCoreWalletPrivateKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.in_addresses.owner_id</code>.
     */
    public void setOwnerId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.in_addresses.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.in_addresses.is_bech32</code>.
     */
    public void setIsBech32(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.in_addresses.is_bech32</code>.
     */
    public Boolean getIsBech32() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Long, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Long, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return InAddresses.IN_ADDRESSES.ID;
    }

    @Override
    public Field<String> field2() {
        return InAddresses.IN_ADDRESSES.ADDRESS;
    }

    @Override
    public Field<String> field3() {
        return InAddresses.IN_ADDRESSES.BTC_CORE_WALLET_PRIVATE_KEY;
    }

    @Override
    public Field<Long> field4() {
        return InAddresses.IN_ADDRESSES.OWNER_ID;
    }

    @Override
    public Field<Boolean> field5() {
        return InAddresses.IN_ADDRESSES.IS_BECH32;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAddress();
    }

    @Override
    public String component3() {
        return getBtcCoreWalletPrivateKey();
    }

    @Override
    public Long component4() {
        return getOwnerId();
    }

    @Override
    public Boolean component5() {
        return getIsBech32();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAddress();
    }

    @Override
    public String value3() {
        return getBtcCoreWalletPrivateKey();
    }

    @Override
    public Long value4() {
        return getOwnerId();
    }

    @Override
    public Boolean value5() {
        return getIsBech32();
    }

    @Override
    public InAddressesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InAddressesRecord value2(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public InAddressesRecord value3(String value) {
        setBtcCoreWalletPrivateKey(value);
        return this;
    }

    @Override
    public InAddressesRecord value4(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public InAddressesRecord value5(Boolean value) {
        setIsBech32(value);
        return this;
    }

    @Override
    public InAddressesRecord values(Long value1, String value2, String value3, Long value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InAddressesRecord
     */
    public InAddressesRecord() {
        super(InAddresses.IN_ADDRESSES);
    }

    /**
     * Create a detached, initialised InAddressesRecord
     */
    public InAddressesRecord(Long id, String address, String btcCoreWalletPrivateKey, Long ownerId, Boolean isBech32) {
        super(InAddresses.IN_ADDRESSES);

        set(0, id);
        set(1, address);
        set(2, btcCoreWalletPrivateKey);
        set(3, ownerId);
        set(4, isBech32);
    }
}
