/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables.records;


import is.toxic.db.data.tables.LastAdSearchParams;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LastAdSearchParamsRecord extends UpdatableRecordImpl<LastAdSearchParamsRecord> implements Record7<Long, Long, Integer, Integer, Integer, BigDecimal, Boolean> {

    private static final long serialVersionUID = 2092125401;

    /**
     * Setter for <code>public.last_ad_search_params.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.last_ad_search_params.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.last_ad_search_params.owner_fk</code>.
     */
    public void setOwnerFk(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.last_ad_search_params.owner_fk</code>.
     */
    public Long getOwnerFk() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.last_ad_search_params.country</code>.
     */
    public void setCountry(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.last_ad_search_params.country</code>.
     */
    public Integer getCountry() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.last_ad_search_params.currency</code>.
     */
    public void setCurrency(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.last_ad_search_params.currency</code>.
     */
    public Integer getCurrency() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.last_ad_search_params.payment_type</code>.
     */
    public void setPaymentType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.last_ad_search_params.payment_type</code>.
     */
    public Integer getPaymentType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.last_ad_search_params.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.last_ad_search_params.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.last_ad_search_params.is_buy</code>.
     */
    public void setIsBuy(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.last_ad_search_params.is_buy</code>.
     */
    public Boolean getIsBuy() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Integer, Integer, Integer, BigDecimal, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Integer, Integer, Integer, BigDecimal, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return LastAdSearchParams.LAST_AD_SEARCH_PARAMS.ID;
    }

    @Override
    public Field<Long> field2() {
        return LastAdSearchParams.LAST_AD_SEARCH_PARAMS.OWNER_FK;
    }

    @Override
    public Field<Integer> field3() {
        return LastAdSearchParams.LAST_AD_SEARCH_PARAMS.COUNTRY;
    }

    @Override
    public Field<Integer> field4() {
        return LastAdSearchParams.LAST_AD_SEARCH_PARAMS.CURRENCY;
    }

    @Override
    public Field<Integer> field5() {
        return LastAdSearchParams.LAST_AD_SEARCH_PARAMS.PAYMENT_TYPE;
    }

    @Override
    public Field<BigDecimal> field6() {
        return LastAdSearchParams.LAST_AD_SEARCH_PARAMS.AMOUNT;
    }

    @Override
    public Field<Boolean> field7() {
        return LastAdSearchParams.LAST_AD_SEARCH_PARAMS.IS_BUY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOwnerFk();
    }

    @Override
    public Integer component3() {
        return getCountry();
    }

    @Override
    public Integer component4() {
        return getCurrency();
    }

    @Override
    public Integer component5() {
        return getPaymentType();
    }

    @Override
    public BigDecimal component6() {
        return getAmount();
    }

    @Override
    public Boolean component7() {
        return getIsBuy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOwnerFk();
    }

    @Override
    public Integer value3() {
        return getCountry();
    }

    @Override
    public Integer value4() {
        return getCurrency();
    }

    @Override
    public Integer value5() {
        return getPaymentType();
    }

    @Override
    public BigDecimal value6() {
        return getAmount();
    }

    @Override
    public Boolean value7() {
        return getIsBuy();
    }

    @Override
    public LastAdSearchParamsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public LastAdSearchParamsRecord value2(Long value) {
        setOwnerFk(value);
        return this;
    }

    @Override
    public LastAdSearchParamsRecord value3(Integer value) {
        setCountry(value);
        return this;
    }

    @Override
    public LastAdSearchParamsRecord value4(Integer value) {
        setCurrency(value);
        return this;
    }

    @Override
    public LastAdSearchParamsRecord value5(Integer value) {
        setPaymentType(value);
        return this;
    }

    @Override
    public LastAdSearchParamsRecord value6(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public LastAdSearchParamsRecord value7(Boolean value) {
        setIsBuy(value);
        return this;
    }

    @Override
    public LastAdSearchParamsRecord values(Long value1, Long value2, Integer value3, Integer value4, Integer value5, BigDecimal value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LastAdSearchParamsRecord
     */
    public LastAdSearchParamsRecord() {
        super(LastAdSearchParams.LAST_AD_SEARCH_PARAMS);
    }

    /**
     * Create a detached, initialised LastAdSearchParamsRecord
     */
    public LastAdSearchParamsRecord(Long id, Long ownerFk, Integer country, Integer currency, Integer paymentType, BigDecimal amount, Boolean isBuy) {
        super(LastAdSearchParams.LAST_AD_SEARCH_PARAMS);

        set(0, id);
        set(1, ownerFk);
        set(2, country);
        set(3, currency);
        set(4, paymentType);
        set(5, amount);
        set(6, isBuy);
    }
}
