/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.data.tables.records;


import is.toxic.db.data.tables.UserEvents;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEventsRecord extends UpdatableRecordImpl<UserEventsRecord> implements Record10<Long, Long, Long, LocalDateTime, Integer, Long, Long, Integer, Long, Long> {

    private static final long serialVersionUID = -1514185509;

    /**
     * Setter for <code>public.user_events.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_events.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_events.creater_id</code>.
     */
    public void setCreaterId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_events.creater_id</code>.
     */
    public Long getCreaterId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_events.receiver_id</code>.
     */
    public void setReceiverId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_events.receiver_id</code>.
     */
    public Long getReceiverId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_events.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_events.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.user_events.type</code>.
     */
    public void setType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_events.type</code>.
     */
    public Integer getType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.user_events.deal_id</code>.
     */
    public void setDealId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_events.deal_id</code>.
     */
    public Long getDealId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.user_events.deal_message_id</code>.
     */
    public void setDealMessageId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_events.deal_message_id</code>.
     */
    public Long getDealMessageId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.user_events.source</code>.
     */
    public void setSource(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user_events.source</code>.
     */
    public Integer getSource() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.user_events.invoice_id</code>.
     */
    public void setInvoiceId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user_events.invoice_id</code>.
     */
    public Long getInvoiceId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.user_events.invoice_payment_id</code>.
     */
    public void setInvoicePaymentId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user_events.invoice_payment_id</code>.
     */
    public Long getInvoicePaymentId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, LocalDateTime, Integer, Long, Long, Integer, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, Long, LocalDateTime, Integer, Long, Long, Integer, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserEvents.USER_EVENTS.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserEvents.USER_EVENTS.CREATER_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserEvents.USER_EVENTS.RECEIVER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return UserEvents.USER_EVENTS.CREATED_AT;
    }

    @Override
    public Field<Integer> field5() {
        return UserEvents.USER_EVENTS.TYPE;
    }

    @Override
    public Field<Long> field6() {
        return UserEvents.USER_EVENTS.DEAL_ID;
    }

    @Override
    public Field<Long> field7() {
        return UserEvents.USER_EVENTS.DEAL_MESSAGE_ID;
    }

    @Override
    public Field<Integer> field8() {
        return UserEvents.USER_EVENTS.SOURCE;
    }

    @Override
    public Field<Long> field9() {
        return UserEvents.USER_EVENTS.INVOICE_ID;
    }

    @Override
    public Field<Long> field10() {
        return UserEvents.USER_EVENTS.INVOICE_PAYMENT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreaterId();
    }

    @Override
    public Long component3() {
        return getReceiverId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Integer component5() {
        return getType();
    }

    @Override
    public Long component6() {
        return getDealId();
    }

    @Override
    public Long component7() {
        return getDealMessageId();
    }

    @Override
    public Integer component8() {
        return getSource();
    }

    @Override
    public Long component9() {
        return getInvoiceId();
    }

    @Override
    public Long component10() {
        return getInvoicePaymentId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreaterId();
    }

    @Override
    public Long value3() {
        return getReceiverId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public Integer value5() {
        return getType();
    }

    @Override
    public Long value6() {
        return getDealId();
    }

    @Override
    public Long value7() {
        return getDealMessageId();
    }

    @Override
    public Integer value8() {
        return getSource();
    }

    @Override
    public Long value9() {
        return getInvoiceId();
    }

    @Override
    public Long value10() {
        return getInvoicePaymentId();
    }

    @Override
    public UserEventsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserEventsRecord value2(Long value) {
        setCreaterId(value);
        return this;
    }

    @Override
    public UserEventsRecord value3(Long value) {
        setReceiverId(value);
        return this;
    }

    @Override
    public UserEventsRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserEventsRecord value5(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public UserEventsRecord value6(Long value) {
        setDealId(value);
        return this;
    }

    @Override
    public UserEventsRecord value7(Long value) {
        setDealMessageId(value);
        return this;
    }

    @Override
    public UserEventsRecord value8(Integer value) {
        setSource(value);
        return this;
    }

    @Override
    public UserEventsRecord value9(Long value) {
        setInvoiceId(value);
        return this;
    }

    @Override
    public UserEventsRecord value10(Long value) {
        setInvoicePaymentId(value);
        return this;
    }

    @Override
    public UserEventsRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, Integer value5, Long value6, Long value7, Integer value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserEventsRecord
     */
    public UserEventsRecord() {
        super(UserEvents.USER_EVENTS);
    }

    /**
     * Create a detached, initialised UserEventsRecord
     */
    public UserEventsRecord(Long id, Long createrId, Long receiverId, LocalDateTime createdAt, Integer type, Long dealId, Long dealMessageId, Integer source, Long invoiceId, Long invoicePaymentId) {
        super(UserEvents.USER_EVENTS);

        set(0, id);
        set(1, createrId);
        set(2, receiverId);
        set(3, createdAt);
        set(4, type);
        set(5, dealId);
        set(6, dealMessageId);
        set(7, source);
        set(8, invoiceId);
        set(9, invoicePaymentId);
    }
}
