/*
 * This file is generated by jOOQ.
 */
package ru.toxic.fancrypto.identity;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.toxic.fancrypto.identity.tables.AspNetRoleClaims;
import ru.toxic.fancrypto.identity.tables.AspNetRoles;
import ru.toxic.fancrypto.identity.tables.AspNetUserClaims;
import ru.toxic.fancrypto.identity.tables.AspNetUserLogins;
import ru.toxic.fancrypto.identity.tables.AspNetUserRoles;
import ru.toxic.fancrypto.identity.tables.AspNetUsers;
import ru.toxic.fancrypto.identity.tables.PersistedGrants;
import ru.toxic.fancrypto.identity.tables.TelegramStates;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_ASP_NET_ROLE_CLAIMS_ROLE_ID = Indexes0.IX_ASP_NET_ROLE_CLAIMS_ROLE_ID;
    public static final Index ROLE_NAME_INDEX = Indexes0.ROLE_NAME_INDEX;
    public static final Index IX_ASP_NET_USER_CLAIMS_USER_ID = Indexes0.IX_ASP_NET_USER_CLAIMS_USER_ID;
    public static final Index IX_ASP_NET_USER_LOGINS_USER_ID = Indexes0.IX_ASP_NET_USER_LOGINS_USER_ID;
    public static final Index IX_ASP_NET_USER_ROLES_ROLE_ID = Indexes0.IX_ASP_NET_USER_ROLES_ROLE_ID;
    public static final Index EMAIL_INDEX = Indexes0.EMAIL_INDEX;
    public static final Index IX_ASP_NET_USERS_TELEGRAM_ID = Indexes0.IX_ASP_NET_USERS_TELEGRAM_ID;
    public static final Index USER_NAME_INDEX = Indexes0.USER_NAME_INDEX;
    public static final Index IX_PERSISTED_GRANTS_CREATION_TIME = Indexes0.IX_PERSISTED_GRANTS_CREATION_TIME;
    public static final Index IX_PERSISTED_GRANTS_LAST_MODIFED = Indexes0.IX_PERSISTED_GRANTS_LAST_MODIFED;
    public static final Index IX_PERSISTED_GRANTS_REMOTE_IP = Indexes0.IX_PERSISTED_GRANTS_REMOTE_IP;
    public static final Index IX_PERSISTED_GRANTS_SUBJECT_ID = Indexes0.IX_PERSISTED_GRANTS_SUBJECT_ID;
    public static final Index IX_TELEGRAM_STATES_TELEGRAM_USER_ID = Indexes0.IX_TELEGRAM_STATES_TELEGRAM_USER_ID;
    public static final Index IX_TELEGRAM_STATES_USER_ID = Indexes0.IX_TELEGRAM_STATES_USER_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index IX_ASP_NET_ROLE_CLAIMS_ROLE_ID = Internal.createIndex("ix_asp_net_role_claims_role_id", AspNetRoleClaims.ASP_NET_ROLE_CLAIMS, new OrderField[] { AspNetRoleClaims.ASP_NET_ROLE_CLAIMS.ROLE_ID }, false);
        public static Index ROLE_NAME_INDEX = Internal.createIndex("role_name_index", AspNetRoles.ASP_NET_ROLES, new OrderField[] { AspNetRoles.ASP_NET_ROLES.NORMALIZED_NAME }, true);
        public static Index IX_ASP_NET_USER_CLAIMS_USER_ID = Internal.createIndex("ix_asp_net_user_claims_user_id", AspNetUserClaims.ASP_NET_USER_CLAIMS, new OrderField[] { AspNetUserClaims.ASP_NET_USER_CLAIMS.USER_ID }, false);
        public static Index IX_ASP_NET_USER_LOGINS_USER_ID = Internal.createIndex("ix_asp_net_user_logins_user_id", AspNetUserLogins.ASP_NET_USER_LOGINS, new OrderField[] { AspNetUserLogins.ASP_NET_USER_LOGINS.USER_ID }, false);
        public static Index IX_ASP_NET_USER_ROLES_ROLE_ID = Internal.createIndex("ix_asp_net_user_roles_role_id", AspNetUserRoles.ASP_NET_USER_ROLES, new OrderField[] { AspNetUserRoles.ASP_NET_USER_ROLES.ROLE_ID }, false);
        public static Index EMAIL_INDEX = Internal.createIndex("email_index", AspNetUsers.ASP_NET_USERS, new OrderField[] { AspNetUsers.ASP_NET_USERS.NORMALIZED_EMAIL }, false);
        public static Index IX_ASP_NET_USERS_TELEGRAM_ID = Internal.createIndex("ix_asp_net_users_telegram_id", AspNetUsers.ASP_NET_USERS, new OrderField[] { AspNetUsers.ASP_NET_USERS.TELEGRAM_ID }, false);
        public static Index USER_NAME_INDEX = Internal.createIndex("user_name_index", AspNetUsers.ASP_NET_USERS, new OrderField[] { AspNetUsers.ASP_NET_USERS.NORMALIZED_USER_NAME }, true);
        public static Index IX_PERSISTED_GRANTS_CREATION_TIME = Internal.createIndex("ix_persisted_grants_creation_time", PersistedGrants.PERSISTED_GRANTS, new OrderField[] { PersistedGrants.PERSISTED_GRANTS.CREATION_TIME }, false);
        public static Index IX_PERSISTED_GRANTS_LAST_MODIFED = Internal.createIndex("ix_persisted_grants_last_modifed", PersistedGrants.PERSISTED_GRANTS, new OrderField[] { PersistedGrants.PERSISTED_GRANTS.LAST_MODIFED }, false);
        public static Index IX_PERSISTED_GRANTS_REMOTE_IP = Internal.createIndex("ix_persisted_grants_remote_ip", PersistedGrants.PERSISTED_GRANTS, new OrderField[] { PersistedGrants.PERSISTED_GRANTS.REMOTE_IP }, false);
        public static Index IX_PERSISTED_GRANTS_SUBJECT_ID = Internal.createIndex("ix_persisted_grants_subject_id", PersistedGrants.PERSISTED_GRANTS, new OrderField[] { PersistedGrants.PERSISTED_GRANTS.SUBJECT_ID }, false);
        public static Index IX_TELEGRAM_STATES_TELEGRAM_USER_ID = Internal.createIndex("ix_telegram_states_telegram_user_id", TelegramStates.TELEGRAM_STATES, new OrderField[] { TelegramStates.TELEGRAM_STATES.TELEGRAM_USER_ID }, false);
        public static Index IX_TELEGRAM_STATES_USER_ID = Internal.createIndex("ix_telegram_states_user_id", TelegramStates.TELEGRAM_STATES, new OrderField[] { TelegramStates.TELEGRAM_STATES.USER_ID }, false);
    }
}
