/*
 * This file is generated by jOOQ.
 */
package ru.toxic.fancrypto.identity;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.toxic.fancrypto.identity.tables.AspNetRoleClaims;
import ru.toxic.fancrypto.identity.tables.AspNetRoles;
import ru.toxic.fancrypto.identity.tables.AspNetUserClaims;
import ru.toxic.fancrypto.identity.tables.AspNetUserLogins;
import ru.toxic.fancrypto.identity.tables.AspNetUserRoles;
import ru.toxic.fancrypto.identity.tables.AspNetUserTokens;
import ru.toxic.fancrypto.identity.tables.AspNetUsers;
import ru.toxic.fancrypto.identity.tables.PersistedGrants;
import ru.toxic.fancrypto.identity.tables.SignIns;
import ru.toxic.fancrypto.identity.tables.TelegramStates;
import ru.toxic.fancrypto.identity.tables.__Efmigrationshistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1271728982;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.__EFMigrationsHistory</code>.
     */
    public final __Efmigrationshistory __EFMIGRATIONSHISTORY = __Efmigrationshistory.__EFMIGRATIONSHISTORY;

    /**
     * The table <code>public.asp_net_role_claims</code>.
     */
    public final AspNetRoleClaims ASP_NET_ROLE_CLAIMS = AspNetRoleClaims.ASP_NET_ROLE_CLAIMS;

    /**
     * The table <code>public.asp_net_roles</code>.
     */
    public final AspNetRoles ASP_NET_ROLES = AspNetRoles.ASP_NET_ROLES;

    /**
     * The table <code>public.asp_net_user_claims</code>.
     */
    public final AspNetUserClaims ASP_NET_USER_CLAIMS = AspNetUserClaims.ASP_NET_USER_CLAIMS;

    /**
     * The table <code>public.asp_net_user_logins</code>.
     */
    public final AspNetUserLogins ASP_NET_USER_LOGINS = AspNetUserLogins.ASP_NET_USER_LOGINS;

    /**
     * The table <code>public.asp_net_user_roles</code>.
     */
    public final AspNetUserRoles ASP_NET_USER_ROLES = AspNetUserRoles.ASP_NET_USER_ROLES;

    /**
     * The table <code>public.asp_net_user_tokens</code>.
     */
    public final AspNetUserTokens ASP_NET_USER_TOKENS = AspNetUserTokens.ASP_NET_USER_TOKENS;

    /**
     * The table <code>public.asp_net_users</code>.
     */
    public final AspNetUsers ASP_NET_USERS = AspNetUsers.ASP_NET_USERS;

    /**
     * The table <code>public.persisted_grants</code>.
     */
    public final PersistedGrants PERSISTED_GRANTS = PersistedGrants.PERSISTED_GRANTS;

    /**
     * The table <code>public.sign_ins</code>.
     */
    public final SignIns SIGN_INS = SignIns.SIGN_INS;

    /**
     * The table <code>public.telegram_states</code>.
     */
    public final TelegramStates TELEGRAM_STATES = TelegramStates.TELEGRAM_STATES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            __Efmigrationshistory.__EFMIGRATIONSHISTORY,
            AspNetRoleClaims.ASP_NET_ROLE_CLAIMS,
            AspNetRoles.ASP_NET_ROLES,
            AspNetUserClaims.ASP_NET_USER_CLAIMS,
            AspNetUserLogins.ASP_NET_USER_LOGINS,
            AspNetUserRoles.ASP_NET_USER_ROLES,
            AspNetUserTokens.ASP_NET_USER_TOKENS,
            AspNetUsers.ASP_NET_USERS,
            PersistedGrants.PERSISTED_GRANTS,
            SignIns.SIGN_INS,
            TelegramStates.TELEGRAM_STATES);
    }
}
