/*
 * This file is generated by jOOQ.
 */
package is.toxic.db.identity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import is.toxic.db.identity.tables.AspNetUserClaims;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AspNetUserClaimsRecord extends UpdatableRecordImpl<AspNetUserClaimsRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = -89484687;

    /**
     * Setter for <code>public.asp_net_user_claims.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asp_net_user_claims.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.asp_net_user_claims.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asp_net_user_claims.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.asp_net_user_claims.claim_type</code>.
     */
    public void setClaimType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asp_net_user_claims.claim_type</code>.
     */
    public String getClaimType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.asp_net_user_claims.claim_value</code>.
     */
    public void setClaimValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asp_net_user_claims.claim_value</code>.
     */
    public String getClaimValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AspNetUserClaims.ASP_NET_USER_CLAIMS.ID;
    }

    @Override
    public Field<String> field2() {
        return AspNetUserClaims.ASP_NET_USER_CLAIMS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return AspNetUserClaims.ASP_NET_USER_CLAIMS.CLAIM_TYPE;
    }

    @Override
    public Field<String> field4() {
        return AspNetUserClaims.ASP_NET_USER_CLAIMS.CLAIM_VALUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getClaimType();
    }

    @Override
    public String component4() {
        return getClaimValue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getClaimType();
    }

    @Override
    public String value4() {
        return getClaimValue();
    }

    @Override
    public AspNetUserClaimsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AspNetUserClaimsRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public AspNetUserClaimsRecord value3(String value) {
        setClaimType(value);
        return this;
    }

    @Override
    public AspNetUserClaimsRecord value4(String value) {
        setClaimValue(value);
        return this;
    }

    @Override
    public AspNetUserClaimsRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AspNetUserClaimsRecord
     */
    public AspNetUserClaimsRecord() {
        super(AspNetUserClaims.ASP_NET_USER_CLAIMS);
    }

    /**
     * Create a detached, initialised AspNetUserClaimsRecord
     */
    public AspNetUserClaimsRecord(Integer id, String userId, String claimType, String claimValue) {
        super(AspNetUserClaims.ASP_NET_USER_CLAIMS);

        set(0, id);
        set(1, userId);
        set(2, claimType);
        set(3, claimValue);
    }
}
