/*
 * This file is generated by jOOQ.
 */
package ru.toxic.fancrypto.identity.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.toxic.fancrypto.identity.Indexes;
import ru.toxic.fancrypto.identity.Keys;
import ru.toxic.fancrypto.identity.Public;
import ru.toxic.fancrypto.identity.tables.records.AspNetRolesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AspNetRoles extends TableImpl<AspNetRolesRecord> {

    private static final long serialVersionUID = -1087629032;

    /**
     * The reference instance of <code>public.asp_net_roles</code>
     */
    public static final AspNetRoles ASP_NET_ROLES = new AspNetRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AspNetRolesRecord> getRecordType() {
        return AspNetRolesRecord.class;
    }

    /**
     * The column <code>public.asp_net_roles.id</code>.
     */
    public final TableField<AspNetRolesRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.asp_net_roles.name</code>.
     */
    public final TableField<AspNetRolesRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.asp_net_roles.normalized_name</code>.
     */
    public final TableField<AspNetRolesRecord, String> NORMALIZED_NAME = createField(DSL.name("normalized_name"), org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.asp_net_roles.concurrency_stamp</code>.
     */
    public final TableField<AspNetRolesRecord, String> CONCURRENCY_STAMP = createField(DSL.name("concurrency_stamp"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.asp_net_roles</code> table reference
     */
    public AspNetRoles() {
        this(DSL.name("asp_net_roles"), null);
    }

    /**
     * Create an aliased <code>public.asp_net_roles</code> table reference
     */
    public AspNetRoles(String alias) {
        this(DSL.name(alias), ASP_NET_ROLES);
    }

    /**
     * Create an aliased <code>public.asp_net_roles</code> table reference
     */
    public AspNetRoles(Name alias) {
        this(alias, ASP_NET_ROLES);
    }

    private AspNetRoles(Name alias, Table<AspNetRolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private AspNetRoles(Name alias, Table<AspNetRolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AspNetRoles(Table<O> child, ForeignKey<O, AspNetRolesRecord> key) {
        super(child, key, ASP_NET_ROLES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROLE_NAME_INDEX);
    }

    @Override
    public UniqueKey<AspNetRolesRecord> getPrimaryKey() {
        return Keys.PK_ASP_NET_ROLES;
    }

    @Override
    public List<UniqueKey<AspNetRolesRecord>> getKeys() {
        return Arrays.<UniqueKey<AspNetRolesRecord>>asList(Keys.PK_ASP_NET_ROLES);
    }

    @Override
    public AspNetRoles as(String alias) {
        return new AspNetRoles(DSL.name(alias), this);
    }

    @Override
    public AspNetRoles as(Name alias) {
        return new AspNetRoles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AspNetRoles rename(String name) {
        return new AspNetRoles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AspNetRoles rename(Name name) {
        return new AspNetRoles(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
