/*
 * This file is generated by jOOQ.
 */
package ru.toxic.db.identity.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.toxic.db.identity.tables.AspNetUserLogins;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AspNetUserLoginsRecord extends UpdatableRecordImpl<AspNetUserLoginsRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 180455598;

    /**
     * Setter for <code>public.asp_net_user_logins.login_provider</code>.
     */
    public void setLoginProvider(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asp_net_user_logins.login_provider</code>.
     */
    public String getLoginProvider() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.asp_net_user_logins.provider_key</code>.
     */
    public void setProviderKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asp_net_user_logins.provider_key</code>.
     */
    public String getProviderKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.asp_net_user_logins.provider_display_name</code>.
     */
    public void setProviderDisplayName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asp_net_user_logins.provider_display_name</code>.
     */
    public String getProviderDisplayName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.asp_net_user_logins.user_id</code>.
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asp_net_user_logins.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AspNetUserLogins.ASP_NET_USER_LOGINS.LOGIN_PROVIDER;
    }

    @Override
    public Field<String> field2() {
        return AspNetUserLogins.ASP_NET_USER_LOGINS.PROVIDER_KEY;
    }

    @Override
    public Field<String> field3() {
        return AspNetUserLogins.ASP_NET_USER_LOGINS.PROVIDER_DISPLAY_NAME;
    }

    @Override
    public Field<String> field4() {
        return AspNetUserLogins.ASP_NET_USER_LOGINS.USER_ID;
    }

    @Override
    public String component1() {
        return getLoginProvider();
    }

    @Override
    public String component2() {
        return getProviderKey();
    }

    @Override
    public String component3() {
        return getProviderDisplayName();
    }

    @Override
    public String component4() {
        return getUserId();
    }

    @Override
    public String value1() {
        return getLoginProvider();
    }

    @Override
    public String value2() {
        return getProviderKey();
    }

    @Override
    public String value3() {
        return getProviderDisplayName();
    }

    @Override
    public String value4() {
        return getUserId();
    }

    @Override
    public AspNetUserLoginsRecord value1(String value) {
        setLoginProvider(value);
        return this;
    }

    @Override
    public AspNetUserLoginsRecord value2(String value) {
        setProviderKey(value);
        return this;
    }

    @Override
    public AspNetUserLoginsRecord value3(String value) {
        setProviderDisplayName(value);
        return this;
    }

    @Override
    public AspNetUserLoginsRecord value4(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public AspNetUserLoginsRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AspNetUserLoginsRecord
     */
    public AspNetUserLoginsRecord() {
        super(AspNetUserLogins.ASP_NET_USER_LOGINS);
    }

    /**
     * Create a detached, initialised AspNetUserLoginsRecord
     */
    public AspNetUserLoginsRecord(String loginProvider, String providerKey, String providerDisplayName, String userId) {
        super(AspNetUserLogins.ASP_NET_USER_LOGINS);

        set(0, loginProvider);
        set(1, providerKey);
        set(2, providerDisplayName);
        set(3, userId);
    }
}
