/*
 * This file is generated by jOOQ.
 */
package ru.toxic.fancrypto.identity.tables.records;


import java.time.LocalDateTime;
import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.toxic.fancrypto.identity.tables.AspNetUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AspNetUsersRecord extends UpdatableRecordImpl<AspNetUsersRecord> {

    private static final long serialVersionUID = -306414240;

    /**
     * Setter for <code>public.asp_net_users.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asp_net_users.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.asp_net_users.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asp_net_users.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.asp_net_users.normalized_user_name</code>.
     */
    public void setNormalizedUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asp_net_users.normalized_user_name</code>.
     */
    public String getNormalizedUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.asp_net_users.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asp_net_users.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.asp_net_users.normalized_email</code>.
     */
    public void setNormalizedEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.asp_net_users.normalized_email</code>.
     */
    public String getNormalizedEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.asp_net_users.email_confirmed</code>.
     */
    public void setEmailConfirmed(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.asp_net_users.email_confirmed</code>.
     */
    public Boolean getEmailConfirmed() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.asp_net_users.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.asp_net_users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.asp_net_users.security_stamp</code>.
     */
    public void setSecurityStamp(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.asp_net_users.security_stamp</code>.
     */
    public String getSecurityStamp() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.asp_net_users.concurrency_stamp</code>.
     */
    public void setConcurrencyStamp(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.asp_net_users.concurrency_stamp</code>.
     */
    public String getConcurrencyStamp() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.asp_net_users.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.asp_net_users.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.asp_net_users.phone_number_confirmed</code>.
     */
    public void setPhoneNumberConfirmed(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.asp_net_users.phone_number_confirmed</code>.
     */
    public Boolean getPhoneNumberConfirmed() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.asp_net_users.two_factor_enabled</code>.
     */
    public void setTwoFactorEnabled(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.asp_net_users.two_factor_enabled</code>.
     */
    public Boolean getTwoFactorEnabled() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.asp_net_users.lockout_end</code>.
     */
    public void setLockoutEnd(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.asp_net_users.lockout_end</code>.
     */
    public OffsetDateTime getLockoutEnd() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.asp_net_users.lockout_enabled</code>.
     */
    public void setLockoutEnabled(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.asp_net_users.lockout_enabled</code>.
     */
    public Boolean getLockoutEnabled() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.asp_net_users.access_failed_count</code>.
     */
    public void setAccessFailedCount(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.asp_net_users.access_failed_count</code>.
     */
    public Integer getAccessFailedCount() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.asp_net_users.two_fa_secret</code>.
     */
    public void setTwoFaSecret(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.asp_net_users.two_fa_secret</code>.
     */
    public String getTwoFaSecret() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.asp_net_users.last_sms_sent</code>.
     */
    public void setLastSmsSent(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.asp_net_users.last_sms_sent</code>.
     */
    public LocalDateTime getLastSmsSent() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.asp_net_users.last_online</code>.
     */
    public void setLastOnline(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.asp_net_users.last_online</code>.
     */
    public LocalDateTime getLastOnline() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.asp_net_users.reference_token</code>.
     */
    public void setReferenceToken(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.asp_net_users.reference_token</code>.
     */
    public String getReferenceToken() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.asp_net_users.reference_token_created_at</code>.
     */
    public void setReferenceTokenCreatedAt(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.asp_net_users.reference_token_created_at</code>.
     */
    public LocalDateTime getReferenceTokenCreatedAt() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>public.asp_net_users.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.asp_net_users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>public.asp_net_users.is_anonymous</code>.
     */
    public void setIsAnonymous(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.asp_net_users.is_anonymous</code>.
     */
    public Boolean getIsAnonymous() {
        return (Boolean) get(21);
    }

    /**
     * Setter for <code>public.asp_net_users.telegram_id</code>.
     */
    public void setTelegramId(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.asp_net_users.telegram_id</code>.
     */
    public Integer getTelegramId() {
        return (Integer) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AspNetUsersRecord
     */
    public AspNetUsersRecord() {
        super(AspNetUsers.ASP_NET_USERS);
    }

    /**
     * Create a detached, initialised AspNetUsersRecord
     */
    public AspNetUsersRecord(String id, String userName, String normalizedUserName, String email, String normalizedEmail, Boolean emailConfirmed, String passwordHash, String securityStamp, String concurrencyStamp, String phoneNumber, Boolean phoneNumberConfirmed, Boolean twoFactorEnabled, OffsetDateTime lockoutEnd, Boolean lockoutEnabled, Integer accessFailedCount, String twoFaSecret, LocalDateTime lastSmsSent, LocalDateTime lastOnline, String referenceToken, LocalDateTime referenceTokenCreatedAt, LocalDateTime createdAt, Boolean isAnonymous, Integer telegramId) {
        super(AspNetUsers.ASP_NET_USERS);

        set(0, id);
        set(1, userName);
        set(2, normalizedUserName);
        set(3, email);
        set(4, normalizedEmail);
        set(5, emailConfirmed);
        set(6, passwordHash);
        set(7, securityStamp);
        set(8, concurrencyStamp);
        set(9, phoneNumber);
        set(10, phoneNumberConfirmed);
        set(11, twoFactorEnabled);
        set(12, lockoutEnd);
        set(13, lockoutEnabled);
        set(14, accessFailedCount);
        set(15, twoFaSecret);
        set(16, lastSmsSent);
        set(17, lastOnline);
        set(18, referenceToken);
        set(19, referenceTokenCreatedAt);
        set(20, createdAt);
        set(21, isAnonymous);
        set(22, telegramId);
    }
}
