/*
 * This file is generated by jOOQ.
 */
package ru.toxic.fancrypto.identity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.toxic.fancrypto.identity.tables.PersistedGrants;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersistedGrantsRecord extends UpdatableRecordImpl<PersistedGrantsRecord> implements Record9<String, String, String, String, LocalDateTime, LocalDateTime, String, String, LocalDateTime> {

    private static final long serialVersionUID = -573498751;

    /**
     * Setter for <code>public.persisted_grants.key</code>.
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.persisted_grants.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.persisted_grants.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.persisted_grants.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.persisted_grants.subject_id</code>.
     */
    public void setSubjectId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.persisted_grants.subject_id</code>.
     */
    public String getSubjectId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.persisted_grants.client_id</code>.
     */
    public void setClientId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.persisted_grants.client_id</code>.
     */
    public String getClientId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.persisted_grants.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.persisted_grants.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.persisted_grants.expiration</code>.
     */
    public void setExpiration(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.persisted_grants.expiration</code>.
     */
    public LocalDateTime getExpiration() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.persisted_grants.data</code>.
     */
    public void setData(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.persisted_grants.data</code>.
     */
    public String getData() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.persisted_grants.remote_ip</code>.
     */
    public void setRemoteIp(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.persisted_grants.remote_ip</code>.
     */
    public String getRemoteIp() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.persisted_grants.last_modifed</code>.
     */
    public void setLastModifed(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.persisted_grants.last_modifed</code>.
     */
    public LocalDateTime getLastModifed() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, LocalDateTime, LocalDateTime, String, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, LocalDateTime, LocalDateTime, String, String, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PersistedGrants.PERSISTED_GRANTS.KEY;
    }

    @Override
    public Field<String> field2() {
        return PersistedGrants.PERSISTED_GRANTS.TYPE;
    }

    @Override
    public Field<String> field3() {
        return PersistedGrants.PERSISTED_GRANTS.SUBJECT_ID;
    }

    @Override
    public Field<String> field4() {
        return PersistedGrants.PERSISTED_GRANTS.CLIENT_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return PersistedGrants.PERSISTED_GRANTS.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return PersistedGrants.PERSISTED_GRANTS.EXPIRATION;
    }

    @Override
    public Field<String> field7() {
        return PersistedGrants.PERSISTED_GRANTS.DATA;
    }

    @Override
    public Field<String> field8() {
        return PersistedGrants.PERSISTED_GRANTS.REMOTE_IP;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return PersistedGrants.PERSISTED_GRANTS.LAST_MODIFED;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getSubjectId();
    }

    @Override
    public String component4() {
        return getClientId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component6() {
        return getExpiration();
    }

    @Override
    public String component7() {
        return getData();
    }

    @Override
    public String component8() {
        return getRemoteIp();
    }

    @Override
    public LocalDateTime component9() {
        return getLastModifed();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getSubjectId();
    }

    @Override
    public String value4() {
        return getClientId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value6() {
        return getExpiration();
    }

    @Override
    public String value7() {
        return getData();
    }

    @Override
    public String value8() {
        return getRemoteIp();
    }

    @Override
    public LocalDateTime value9() {
        return getLastModifed();
    }

    @Override
    public PersistedGrantsRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value3(String value) {
        setSubjectId(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value4(String value) {
        setClientId(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value5(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value6(LocalDateTime value) {
        setExpiration(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value7(String value) {
        setData(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value8(String value) {
        setRemoteIp(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord value9(LocalDateTime value) {
        setLastModifed(value);
        return this;
    }

    @Override
    public PersistedGrantsRecord values(String value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, String value7, String value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersistedGrantsRecord
     */
    public PersistedGrantsRecord() {
        super(PersistedGrants.PERSISTED_GRANTS);
    }

    /**
     * Create a detached, initialised PersistedGrantsRecord
     */
    public PersistedGrantsRecord(String key, String type, String subjectId, String clientId, LocalDateTime creationTime, LocalDateTime expiration, String data, String remoteIp, LocalDateTime lastModifed) {
        super(PersistedGrants.PERSISTED_GRANTS);

        set(0, key);
        set(1, type);
        set(2, subjectId);
        set(3, clientId);
        set(4, creationTime);
        set(5, expiration);
        set(6, data);
        set(7, remoteIp);
        set(8, lastModifed);
    }
}
