/*
 * This file is generated by jOOQ.
 */
package ru.toxic.fancrypto.data.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.toxic.fancrypto.data.tables.InTransactions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InTransactionsRecord extends UpdatableRecordImpl<InTransactionsRecord> implements Record6<Long, String, Long, BigDecimal, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1752179624;

    /**
     * Setter for <code>public.in_transactions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.in_transactions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.in_transactions.tx_id</code>.
     */
    public void setTxId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.in_transactions.tx_id</code>.
     */
    public String getTxId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.in_transactions.address_id</code>.
     */
    public void setAddressId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.in_transactions.address_id</code>.
     */
    public Long getAddressId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.in_transactions.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.in_transactions.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.in_transactions.confirmations</code>.
     */
    public void setConfirmations(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.in_transactions.confirmations</code>.
     */
    public Integer getConfirmations() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.in_transactions.time</code>.
     */
    public void setTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.in_transactions.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Long, BigDecimal, Integer, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Long, BigDecimal, Integer, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return InTransactions.IN_TRANSACTIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return InTransactions.IN_TRANSACTIONS.TX_ID;
    }

    @Override
    public Field<Long> field3() {
        return InTransactions.IN_TRANSACTIONS.ADDRESS_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return InTransactions.IN_TRANSACTIONS.AMOUNT;
    }

    @Override
    public Field<Integer> field5() {
        return InTransactions.IN_TRANSACTIONS.CONFIRMATIONS;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return InTransactions.IN_TRANSACTIONS.TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTxId();
    }

    @Override
    public Long component3() {
        return getAddressId();
    }

    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    @Override
    public Integer component5() {
        return getConfirmations();
    }

    @Override
    public LocalDateTime component6() {
        return getTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTxId();
    }

    @Override
    public Long value3() {
        return getAddressId();
    }

    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    @Override
    public Integer value5() {
        return getConfirmations();
    }

    @Override
    public LocalDateTime value6() {
        return getTime();
    }

    @Override
    public InTransactionsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InTransactionsRecord value2(String value) {
        setTxId(value);
        return this;
    }

    @Override
    public InTransactionsRecord value3(Long value) {
        setAddressId(value);
        return this;
    }

    @Override
    public InTransactionsRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public InTransactionsRecord value5(Integer value) {
        setConfirmations(value);
        return this;
    }

    @Override
    public InTransactionsRecord value6(LocalDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public InTransactionsRecord values(Long value1, String value2, Long value3, BigDecimal value4, Integer value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InTransactionsRecord
     */
    public InTransactionsRecord() {
        super(InTransactions.IN_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised InTransactionsRecord
     */
    public InTransactionsRecord(Long id, String txId, Long addressId, BigDecimal amount, Integer confirmations, LocalDateTime time) {
        super(InTransactions.IN_TRANSACTIONS);

        set(0, id);
        set(1, txId);
        set(2, addressId);
        set(3, amount);
        set(4, confirmations);
        set(5, time);
    }
}
