/*
 * This file is generated by jOOQ.
 */
package ru.toxic.db.data.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.toxic.db.data.tables.OutTransactions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OutTransactionsRecord extends UpdatableRecordImpl<OutTransactionsRecord> implements Record9<Long, String, String, BigDecimal, Integer, LocalDateTime, BigDecimal, String, Long> {

    private static final long serialVersionUID = 1702363151;

    /**
     * Setter for <code>public.out_transactions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.out_transactions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.out_transactions.tx_id</code>.
     */
    public void setTxId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.out_transactions.tx_id</code>.
     */
    public String getTxId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.out_transactions.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.out_transactions.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.out_transactions.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.out_transactions.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.out_transactions.confirmations</code>.
     */
    public void setConfirmations(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.out_transactions.confirmations</code>.
     */
    public Integer getConfirmations() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.out_transactions.time</code>.
     */
    public void setTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.out_transactions.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.out_transactions.fee</code>.
     */
    public void setFee(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.out_transactions.fee</code>.
     */
    public BigDecimal getFee() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.out_transactions.wallet_private_key</code>.
     */
    public void setWalletPrivateKey(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.out_transactions.wallet_private_key</code>.
     */
    public String getWalletPrivateKey() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.out_transactions.request_id</code>.
     */
    public void setRequestId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.out_transactions.request_id</code>.
     */
    public Long getRequestId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, BigDecimal, Integer, LocalDateTime, BigDecimal, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, BigDecimal, Integer, LocalDateTime, BigDecimal, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OutTransactions.OUT_TRANSACTIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return OutTransactions.OUT_TRANSACTIONS.TX_ID;
    }

    @Override
    public Field<String> field3() {
        return OutTransactions.OUT_TRANSACTIONS.ADDRESS;
    }

    @Override
    public Field<BigDecimal> field4() {
        return OutTransactions.OUT_TRANSACTIONS.AMOUNT;
    }

    @Override
    public Field<Integer> field5() {
        return OutTransactions.OUT_TRANSACTIONS.CONFIRMATIONS;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return OutTransactions.OUT_TRANSACTIONS.TIME;
    }

    @Override
    public Field<BigDecimal> field7() {
        return OutTransactions.OUT_TRANSACTIONS.FEE;
    }

    @Override
    public Field<String> field8() {
        return OutTransactions.OUT_TRANSACTIONS.WALLET_PRIVATE_KEY;
    }

    @Override
    public Field<Long> field9() {
        return OutTransactions.OUT_TRANSACTIONS.REQUEST_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTxId();
    }

    @Override
    public String component3() {
        return getAddress();
    }

    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    @Override
    public Integer component5() {
        return getConfirmations();
    }

    @Override
    public LocalDateTime component6() {
        return getTime();
    }

    @Override
    public BigDecimal component7() {
        return getFee();
    }

    @Override
    public String component8() {
        return getWalletPrivateKey();
    }

    @Override
    public Long component9() {
        return getRequestId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTxId();
    }

    @Override
    public String value3() {
        return getAddress();
    }

    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    @Override
    public Integer value5() {
        return getConfirmations();
    }

    @Override
    public LocalDateTime value6() {
        return getTime();
    }

    @Override
    public BigDecimal value7() {
        return getFee();
    }

    @Override
    public String value8() {
        return getWalletPrivateKey();
    }

    @Override
    public Long value9() {
        return getRequestId();
    }

    @Override
    public OutTransactionsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value2(String value) {
        setTxId(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value3(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value5(Integer value) {
        setConfirmations(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value6(LocalDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value7(BigDecimal value) {
        setFee(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value8(String value) {
        setWalletPrivateKey(value);
        return this;
    }

    @Override
    public OutTransactionsRecord value9(Long value) {
        setRequestId(value);
        return this;
    }

    @Override
    public OutTransactionsRecord values(Long value1, String value2, String value3, BigDecimal value4, Integer value5, LocalDateTime value6, BigDecimal value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OutTransactionsRecord
     */
    public OutTransactionsRecord() {
        super(OutTransactions.OUT_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised OutTransactionsRecord
     */
    public OutTransactionsRecord(Long id, String txId, String address, BigDecimal amount, Integer confirmations, LocalDateTime time, BigDecimal fee, String walletPrivateKey, Long requestId) {
        super(OutTransactions.OUT_TRANSACTIONS);

        set(0, id);
        set(1, txId);
        set(2, address);
        set(3, amount);
        set(4, confirmations);
        set(5, time);
        set(6, fee);
        set(7, walletPrivateKey);
        set(8, requestId);
    }
}
